- .s2i/bin/assemble
- Rakefile
- config/environments/production.rb
augments the sit assembly step to run npm install and to precompile the webpack assets which isnt supported by the base assembly script
> Asset precompile

- app/models/question.rb
- app/models/response_set.rb
- app/views/questions/_question_details.html.erb
- app/views/questions/show.html.erb
- app/views/response_sets/show.html.erb
- db/schema.rb
This PR adds a display of the current version and version currently selected on the show page for both response sets and questions. Please review how it looks and let me know any stylistic changes that should be made.
> Current Version Display for Questions and Response Sets

- .rubocop.yml
- app/controllers/forms_controller.rb
- app/views/forms/export.html.erb
- app/views/forms/new.html.erb
- app/views/forms/show.html.erb
- app/views/responses/edit.html.erb
- config/routes.rb
- features/manage_forms.feature
- features/step_definitions/response_set_steps.rb
- webpack/styles/layouts/_footer.scss
- webpack/styles/layouts/_printview.scss
- webpack/styles/master.scss
Added an export button to the show page of a form. Steps to test:
- Create a form with the questions linked to *response sets with responses* (it will enumerate the responses as options on the export page)
- Go to the forms show page and click the `Export` link at the bottom (also fixed a bug here with form revision being allowed on previous versions, similar to the q/rs bug that was previously fixed)
- This page shows a preview, but if you click the export button it will open up a print / print as pdf browser prompt that should strip out the unnecessary elements and just yield the form contents.
- [n/a] If any database changes were made, run `rake generate_erd` …
> Form Exporting

- .eslintrc
- app/views/layouts/application.html.erb
- app/views/response_sets/_form.html.erb
- config/webpack.config.js
- db/schema.rb
- test/frontend/components/question_list_test.js
- test/frontend/components/response_set_table_test.js
- test/frontend/mock_routes.js
- webpack/application.js
- webpack/camelcase.js
- webpack/components/QuestionItem.js
- webpack/components/QuestionWidget.js
- webpack/components/ResponseSetList.js
- webpack/components/ResponseSetTable.js
- webpack/components/ResponseSetWidget.js
- webpack/components/SearchBar.js
- webpack/components/SearchWidget.js
- webpack/components/SearchWidgetBar.js
- webpack/containers/QuestionSearch.js
- webpack/reducers/index.js
- webpack/response_set_list.js
- webpack/routes.js
- webpack/search.js
This PR changes some of the eslint rules to better enforce our JavaScript coding style. It will enforce whitespace rules as well as making sure that variable names are camelCase. Several changes were required to make this happen.
In some places, serialization of objects from the Rails side were modified so that JSON property names are in camelCase.
The route helper library was augmented so that there are functions for routes in camelCase.
Lastly, babel-polyfill was pulled out to a webpack entry point. This means that individual files don't have to worry about including it. It also eliminates the issue where multiple files pull it in and it throws an error in the browser.
- N/A Added unit tests for new …
> eslint [SDP-234]

- app/views/questions/_form.html.erb
- webpack/components/QuestionForm.js
In changing parts of the web form from ERb to a React component, the
version and version_independent_id we not getting properly populated
in the web form. This commit pulls those field out of the React
component and puts them back in the ERb.
- N/A Added unit tests for new functionality - bug fix
- N/A Added cucumber tests for any new functionality - bug fix
> Fixes issue preventing revising Questions

- .eslintrc
- webpack/components/SearchWidget.js
- webpack/reducers/comments.js
- webpack/reducers/questions.js
The .eslintrc now follows our indenting rules
Now all double quotes in the .eslintrc file so it is valid JSON
SwitchCase indenting now follows @rdingwell's preferred style
- N/A Added cucumber tests for any new functionality
> Some clean up for eslint

- features/support/env.rb
Previously, when tests were run, you would see messages like:
"%c prev state color: #9E9E9E; font-weight: bold [object Object]"
This was caused by the redux.js logging tools. By default the
combination of cucumber, Capybara, Poltergeist and PhantomJS write
JavaScript console.log messages to standard out. This change configures
that logging to go to a file in the log directory.
- N/A Added cucumber tests for any new functionality
> Eliminate console.log messages during testing

- app/controllers/forms_controller.rb
- app/views/forms/_form.html.erb
- features/manage_forms.feature
- webpack/forms.js
Previously, if you tried to save a form, but it had an error, like
an invalid OMB control number, you would lose the selected questions
when the page reloaded.
This addresses the issue by saving the form in an AJAX request. If
the save is successful, it redirects the browser to the form show
page. If it fails, it shows the error on the page.
The code is kind of gross in that in mixes jQuery and React/Redux.
This is due to the fact that we are trying to save work on the React
side by using the form helper stuff from Rails. This should all be
refactored so that the form is created and managed by React.
- N/A If any database changes were made, run `rake generate_erd` …
> Fixes form content being lost when trying to save [SDP-242]

- test/frontend/components/response_set_list_search_test.js
- test/frontend/components/response_set_list_test.js
- test/frontend/mock_routes.js
- webpack/actions/response_set_actions.js
- webpack/components/Header.js
- webpack/components/ResponseSetListSearch.js
- webpack/containers/DashboardContainer.js
- webpack/containers/ResponseSetShowContainer.js
- webpack/containers/ResponseSetsContainer.js
- webpack/styles/layouts/_panels.scss
- webpack/styles/navigation/_nav.scss
- webpack/styles/widgets/_analytics.scss
Finished up SDP-289 - Convert index page for Response Sets into React component
Implemented search on the response set's Index page the same as it was implemented on the forms and questions index pages.
Also did some minor cleanup to the css to get it back toward Eny's mockups. 
- [n/a] Passed all cucumber tests using `bundle exec cucumber`
> Search on Response set Index page - Finishing SDP-289

- app/views/response_sets/_response_set.json.jbuilder
- test/frontend/middleware/test_parent_from_response_sets.js
- test/frontend/reducers/test_response_sets.js
- webpack/components/ResponseSetDetails.js
- webpack/components/ResponseSetForm.js
- webpack/components/VersionInfo.js
- webpack/containers/FormShowContainer.js
- webpack/containers/QuestionShowContainer.js
- webpack/containers/ResponseSetShowContainer.js
- webpack/middleware/parent_from_response_sets.js
- webpack/prop-types/response_set_props.js
- webpack/store/configure_store.js
Response Set Parent, Versioning, and Reducer tests added. Fixed a bug when component is updated with a new id but not re-rendered.
Details:
The Response set extend functionality was not properly linking the parent. The links on the component pages would not re-render components and thus the parent or previous version would not be in the store, causing it to never render.
Acceptance Criteria:
Can click on the 'Extended from' link or the previous versions link on a RS show page and have it navigate successfully in the new react SPA.
- [n/a] Passed all cucumber tests using `bundle exec cucumber`
- [n/a] If any database changes were made, run `rake …
> [SDP-318] Response Set Parent, Versioning, and Reducer tests added

- test/frontend/components/errors_test.js
- webpack/actions/response_set_actions.js
- webpack/components/Errors.js
- webpack/components/ResponseSetForm.js
This completes SDP-277. The component now properly handles and displays when the server returns an error when saving a response set.
> Handle errors on Response Set Save [SDP-277]

- app/views/response_sets/_response_set.json.jbuilder
- package.json
- test/frontend/components/errors_test.js
- test/frontend/components/version_info_test.js
- test/frontend/selectors/test_response_set_selectors.js
- webpack/actions/response_set_actions.js
- webpack/components/Errors.js
- webpack/components/ResponseSetForm.js
- webpack/components/VersionInfo.js
- webpack/containers/QuestionEditContainer.js
- webpack/containers/ResponseSetsContainer.js
- webpack/selectors/response_set_selectors.js
Please review #103 before this PR.
Previously, the response set index page and the question edit pages
would show all versions of response sets. This commit narrows those
pages down to just the most recent version of each response set.
This uses selectors, via the reselect library, to filter down the
redux state.
This commit also cleans up and tests the VersionInfo component. It
previously relied on the allVersions and otherVersions properties.
It now relies only on allVersions. otherVersions were removed from
the server side JSON response to minimize the amount of data being
sent around.
> Only showing most recent versions of response sets

- Gemfile
- Gemfile.lock
- features/step_definitions/common_steps.rb
- features/support/env.rb
- setup_headless_testing.sh
Added content for the HEADLESS option when running cucumber tests for the sake of all of our Ubuntu 16.04 developer.
To run cucumber tests headlessly in Ubuntu 16.04 run the provided setup script, then install as normal
`./setup_headless_testing.sh; npm install; bundle install;`
When running cucumber tests, use the 'HEADLESS' environment variable to run tests using webkit.
`HEADLESS=true bundle exec cucumber`
`HEADLESS=true bundle exec rake`
`HEADLESS=true cucumber features/manage_forms.feature --fail-fast`
> [SDP-297] Headless cucumber test option

- features/manage_questions.feature
- webpack/components/Comment.js
- webpack/components/CommentForm.js
Now says "Post" instead of "Send"
Fixed a number of a11y issues as flagged by cucumber
> [SDP-326] Revised wording for comment submit button 

- test/frontend/mock_routes.js
- webpack/prop-types/route_props.js
The revise form route went away but allRoutes still had it as required, so there was an annoying warning on page loads. No jira issue, just saw this and wanted to fix it quick.
> Fixing annoying proptypes warning

- features/manage_questions.feature
- package.json
- test/frontend/components/modal_dialog_test.js
- test/frontend/mock_router.js
- webpack/components/ModalDialog.js
- webpack/components/QuestionForm.js
- webpack/prop-types/current_user_props.js
- webpack/prop-types/response_set_props.js
First try using react-bootstrap, only did the question page so far. iIf we like it i'll add to response sets and forms.
> [SDP-327] Adding new and improved user save warning dialog

- app/views/forms/_form.json.jbuilder
- features/manage_forms.feature
- features/manage_questions.feature
- features/step_definitions/form_steps.rb
- features/step_definitions/question_steps.rb
- test/frontend/components/question_details_test.js
- webpack/components/FormEdit.js
- webpack/components/FormShow.js
- webpack/components/QuestionDetails.js
- webpack/components/QuestionForm.js
Description appears in ui for forms, response sets, questions. Tweaked cucumber tests, but they still fail for unrelated reasons.
> [SDP-86]Add description to ui

- app/controllers/api/application_controller.rb
- app/controllers/api/forms_controller.rb
- app/controllers/api/questions_controller.rb
- app/controllers/api/response_sets_controller.rb
- app/serializers/form_questions_serializer.rb
- test/controllers/api/forms_controller_test.rb
- test/controllers/api/questions_controller_test.rb
- test/controllers/api/response_sets_controller_test.rb
API now produces json when errors occur
API no longer fails when question on form has no response set
Added relevant tests
> [SDP-238] Modified API error handling

- features/support/env.rb
- webpack/containers/Header.js
- webpack/styles/layouts/_body.scss
Fixed the issue when on outernet using Fakeweb and got rid of fixed nav bar
> [SDP-No #] Cucumber Nav and Outernet Fixes

- test/frontend/components/form_edit_test.js
- test/frontend/components/form_list_test.js
- test/frontend/components/form_question_list_test.js
- test/frontend/components/form_widget_test.js
- test/frontend/components/question_details_test.js
- test/frontend/components/question_form_test.js
- test/frontend/components/question_list_test.js
- test/frontend/components/question_widget_test.js
- test/frontend/components/response_set_form_test.js
- test/frontend/components/response_set_list_test.js
- test/frontend/components/search_result_test.js
- test/frontend/containers/coded_set_table_edit_container_test.js
- test/frontend/containers/question_edit_container_test.js
- test/frontend/containers/question_show_container_test.js
- test/frontend/mock_routes.js
- webpack/components/FormList.js
- webpack/components/FormQuestionList.js
- webpack/components/FormWidget.js
- webpack/components/QuestionDetails.js
- webpack/components/QuestionWidget.js
- webpack/components/ResponseSetList.js
- webpack/components/ResponseSetWidget.js
- webpack/components/SearchWidget.js
If a component needs to access Rails routes, it now imports them
directly. Using Rails routes in the components should be avoided anyway
since hitting the server should be done in actions.
Removed the mock_routes as they are no longer needed by the test suite.
Fixed many eslint issues in the tests. Not all, as we have some
commented code in there that we may enable later, but creates some
unused variables.
- [NA] Added unit tests for new functionality
- [NA] Added cucumber tests for any new functionality
- [NA] If any database changes were made, run `rake generate_erd` to update the README.md
- [NA] If any changes …
> [SDP-353] No longer passing routes as props

- webpack/actions/concepts_actions.js
- webpack/containers/CodedSetTableEditContainer.js
- webpack/styles/widgets/_modal.scss
The UI and backing code is updated, works with either version of the concept microservice, can't see it working yet because the new version of the microservice isn't up yet. When it is updated, this code will just work.
> [SDP-404] Updating concept search modal to work without selecting a system

- features/manage_forms.feature
- features/manage_questions.feature
- features/manage_response_sets.feature
- features/step_definitions/common_steps.rb
- test/frontend/components/form_edit_test.js
- test/frontend/components/response_set_form_test.js
- webpack/components/FormEdit.js
- webpack/components/QuestionForm.js
- webpack/components/QuestionResults.js
- webpack/components/ResponseSetDragWidget.js
- webpack/components/ResponseSetForm.js
- webpack/components/ResponseSetModal.js
- webpack/containers/FormsEditContainer.js
- webpack/containers/QuestionModalContainer.js
- webpack/styles/layouts/_form_edit.scss
- webpack/styles/master.scss
- webpack/styles/widgets/_questions.scss
- webpack/styles/widgets/_response_set_modal.scss
Create a new response set from Question form and Form form.
- This should be refactored so QuestionForm isn't responsible for the response set modal, but I've already spent too much time on this and we have other priorities
> [SDP-366, 380] New responseset modal

- features/step_definitions/common_steps.rb
- features/step_definitions/form_steps.rb
- features/step_definitions/question_steps.rb
- features/step_definitions/response_set_steps.rb
- features/support/env.rb
- lib/sdp/elastic_search.rb
Implemented according to latest discussion encapsulated here:
Ammu Irivinti added a comment - 13/Mar/17 10:15 AM - edited
3/13 Sprint Planning:
Defining relevance for now as:
1. search term appears in content title
2. search term appears in associated concepts
Including the associated response sets / response codes may dilute the actual relevant search result.
Deferring usage (programs & systems using content) as prioritization metric, because this is not currently implemented in the system. Wrote a separate story to handle this in a later Sprint.
- [n/a] If any database …
> [SDP-392] Boosted query

- app/controllers/landing_controller.rb
- app/views/surveys/_survey.json.jbuilder
- features/manage_response_sets.feature
- features/manage_surveys.feature
- features/step_definitions/common_steps.rb
- features/step_definitions/survey_steps.rb
- test/elastic_helpers.rb
- webpack/components/SearchResult.js
- webpack/components/SearchResultList.js
- webpack/components/surveys/Show.js
- webpack/containers/DashboardContainer.js
- webpack/prop-types/survey_props.js
- webpack/styles/widgets/_analytics.scss
This adds Surveys to the dashboard and hooks them into search result widget using elastic search.
I also added some of the cucumber rules and simple tests for the index page and details page to start until the creation and editing workflow is in.
> [SDP-419 & SDP-428] Survey on dashboard analytics widget and search results

- features/session.feature
- webpack/components/accounts/ProfileEditor.js
- webpack/components/accounts/SettingsModal.js
- webpack/components/accounts/SignUpModal.js
If there are no surveillance systems or programs in the database, the
UI will say that. Makes sure that there are no programs or systems sent
to the server when submitting the request.
This commit also extracts common functionality between the SettingsModal
and the SignUpModal into the new ProfileEditor component.
> [SDP-438] Profile edits w/o systems or programs in DB

- test/frontend/middleware/test_questions_from_forms.js
- test/frontend/middleware/test_response_sets_from_questions.js
- webpack/middleware/parent_from_questions.js
- webpack/middleware/parent_from_response_sets.js
- webpack/middleware/question_types_from_questions.js
- webpack/middleware/questions_from_forms.js
- webpack/middleware/questions_from_response_sets.js
- webpack/middleware/response_sets_from_questions.js
- webpack/middleware/response_types_from_questions.js
- webpack/middleware/store_helper.js
The middleware in the application will look through nested objects that are returned by fetch actions. It will then try to put those objects into the store in the correct location. The problem is that sometimes the child object contains less information than if it were fetched directly. Previous behavior would allow these child objects to overwrite existing objects in the store, causing information loss on the client side.
This PR changes the middleware behavior so that it will check to see if the child object is present in the store before dispatching an action to update the store with the child object. If there is already an object in the store with the same id, the child object is ignored and the code moves on.
> [SDP-445] Prevent middleware overwriting with child objects

- app/controllers/landing_controller.rb
- docs/elastic_search_schema.json
- features/cancel_buttons.feature
- webpack/components/SurveyEdit.js
- webpack/containers/App.js
- webpack/containers/DashboardContainer.js
- webpack/containers/Header.js
Implemented the four shorter tasks / bug fixes for this sprint including:
- Changing the placeholder on the right side of the dashboard to match most recent mockups (showing mystuff instead of repeating analytics widget)
- Switched Elasticsearch tokenizer to use edge n-grams and take out the default common stop words
- *PLEASE NOTE*: In order to test / see this take place I recommend DELETE-ing the /vocabulary index in your local ES, then hooking into the rails console for your app and running: `SDP::Elasticsearch.ensure_index` followed by `SDP::Elasticsearch.sync`, otherwise the app will hang for awhile on the first save while you wait for the ES index to be setup
- Fixed cancel button on the survey edit page to behave the same as the others (redirect to dashboard)
- OBE'd the navigation …
> [SDP- 398, 435, 447, 448] Short bugfixes / tasks

- features/draft_questions.feature
- features/manage_questions.feature
- test/frontend/components/response_set_drag_widget_test.js
- webpack/components/Draggable.js
- webpack/components/NestedSearchBar.js
- webpack/components/ResponseSetDragWidget.js
- webpack/components/SearchResult.js
- webpack/styles/widgets/_responseset.scss
This PR does the following (behavior should be tested / checked):
- The drag and drop objects on the question edit page now turn the cursor into a grab hand to make that function more apparent
- The question edit page now has a search and uses elastic search and load more functionality to populate available response sets for association
- Question edit page now uses the updated widget
- Question edit response set association can now be done through the + button in the bottom right of the widget instead of solely by drag and drop
> [SDP-379,469] ES on Question Edit and New Response Set Association Method 

- features/step_definitions/common_steps.rb
- webpack/components/Draggable.js
- webpack/components/FormEdit.js
- webpack/components/QuestionItem.js
- webpack/components/SearchResult.js
- webpack/components/SearchResultList.js
- webpack/containers/DashboardContainer.js
- webpack/containers/FormSearchContainer.js
- webpack/containers/QuestionSearchContainer.js
Making it harder to get to details page from edit pages. 
- na Added unit tests for new functionality
> [SDP-453] Disable details link

- app/controllers/forms_controller.rb
- app/models/survey.rb
- features/edit_forms.feature
- features/step_definitions/form_steps.rb
- test/frontend/components/form_question_list_test.js
- test/frontend/reducers/test_response_sets.js
- webpack/components/FormEdit.js
- webpack/components/FormQuestionList.js
- webpack/components/FormShow.js
- webpack/components/QuestionItem.js
- webpack/components/SearchResult.js
- webpack/containers/DashboardContainer.js
- webpack/containers/FormShowContainer.js
- webpack/containers/FormsEditContainer.js
- webpack/containers/surveys/ShowContainer.js
- webpack/reducers/forms_reducer.js
- webpack/reducers/response_sets_reducer.js
This PR:
- Makes it so reordering a question on form edit keeps the response set associated with it
- Uses the updated widget design on form details page and edits the widget to handle FormQuestions when passed in
- adds comments to surveys
> [SDP-442,464] Fix Question and RS order on Form Edit & Comments on Surveys

- lib/sdp/elastic_search.rb
- webpack/components/SearchResult.js
- webpack/containers/DashboardContainer.js
I made three small changes based on bugs I noticed that weren't addressed and things that came up in sprint review:
1) When backup search is used and there are 0 search results returned there was a 0 displaying floating in the middle of page (noticed on dev server)
2) Elastic search was returning all queries that met the filters and sorting them based on the query made, now when you query with a search term it only returns results that match that term in one of the fields
3) Fixed a highlighting bug that was introduced by a rebase yesterday, name of items should now properly highlight when partial word was matched.
- …
> [SDP-None] Mid sprint fixing a few visual

- app/controllers/questions_controller.rb
- app/controllers/response_sets_controller.rb
- app/models/form.rb
- app/models/question.rb
- app/models/response_set.rb
- app/serializers/es_form_serializer.rb
- app/serializers/es_question_serializer.rb
- app/serializers/es_response_set_serializer.rb
- test/fixtures/form_questions.yml
- test/fixtures/surveillance_systems.yml
- test/fixtures/survey_forms.yml
- test/fixtures/surveys.yml
- test/models/question_test.rb
- test/models/response_set_test.rb
- webpack/components/SearchResult.js
Also provides some fixes for ES serializers and resulting clean up in
other places.
This doesn't really add any new functionality. Just hooks up to what was already there.
> [SDP-385] Show usage count on widgets

- webpack/components/FormQuestionList.js
This component was mutating objects passed in as props. Those props were
objects from the redux store. Since they are all references to the same
object, mutating them will mutate the redux store, which is bad.
This change creates a clone of the object before mutating it and passing
it along to another component.
> [SDP-498] Fix bug breaking redux store shape

- features/session.feature
- features/usage.feature
- webpack/components/accounts/LogInModal.js
- webpack/containers/QuestionShowContainer.js
- webpack/containers/ResponseSetShowContainer.js
Tests are written to fully test and satisfy the conditions / workflow outlined in the the refresh usage story, cucumber is not using the navigation shortcuts / database shortcuts to lessen the workflow.
> [SDP-484,485] Refresh on Login, Refresh Usage without refreshing app

- app/controllers/authentications_controller.rb
- app/controllers/elasticsearch_controller.rb
- app/models/concerns/searchable.rb
- lib/sdp/elastic_search.rb
- lib/sdp/simple_search.rb
- test/fixtures/roles.yml
- test/fixtures/users.yml
- test/unit/lib/elastic_search_test.rb
- test/unit/lib/simple_search_test.rb
- webpack/components/FormEdit.js
- webpack/components/ResponseSetDragWidget.js
- webpack/components/SurveyEdit.js
- webpack/containers/FormSearchContainer.js
- webpack/containers/FormsEditContainer.js
- webpack/containers/QuestionSearchContainer.js
- webpack/containers/SurveyEditContainer.js
Current User in the store now has a `publisher` key that stores a `true` if the current_user.has_role? :publisher unblocking UI conditional rendering stories @schreiaj 
The backup search and elastic search now take into account wether the current_user is a publisher as well and return 
A lot of refactoring was done to the ES module to reduce redundancy and accommodate the new changes.
> [SDP-466,476] Publisher Search on Drafts, updated Current User Serializer

- app/models/survey_form.rb
- test/controllers/survey_controller_test.rb
> [SDP-506] Ensure ES is updated for child objects of survey

- app/controllers/elasticsearch_controller.rb
- lib/sdp/elastic_search.rb
- webpack/actions/search_results_actions.js
- webpack/components/DashboardSearch.js
- webpack/components/QuestionItem.js
- webpack/containers/DashboardContainer.js
- webpack/containers/FormSearchContainer.js
- webpack/containers/QuestionSearchContainer.js
- webpack/styles/widgets/_search.scss
Adds advanced search to applicable search bars, when applying a new filter it updates the results with the filter applied. If elastic search is down it displays a message letting the user know it is down.
> [SDP-482] Advanced / Prog & sys search filter

- lib/sdp/importers/cdc.rb
- lib/sdp/importers/jupiter.rb
- lib/tasks/programs_and_systems.rake
- test/fixtures/files/jupiter_response.json
- test/unit/lib/jupiter_test.rb
Contains rake tasks to import surveillance programs and systems from two things:
* An internally generated CDC excel file
* Jupiter - http://jupiter.phiresearchlab.org/
> [SDP-490] Program and system import

- features/manage_forms.feature
- features/manage_questions.feature
- features/manage_response_sets.feature
- features/manage_surveys.feature
- features/step_definitions/common_steps.rb
- package.json
- webpack/actions/publisher_actions.js
- webpack/actions/types.js
- webpack/components/FormShow.js
- webpack/components/QuestionDetails.js
- webpack/components/ResponseSetDetails.js
- webpack/components/shared_show/PublisherLookUp.js
- webpack/components/surveys/Show.js
- webpack/containers/App.js
- webpack/containers/FormShowContainer.js
- webpack/containers/QuestionShowContainer.js
- webpack/containers/ResponseSetShowContainer.js
- webpack/containers/surveys/ShowContainer.js
- webpack/prop-types/publisher_props.js
- webpack/reducers/index.js
Provides a "Send to publisher" button on the show pages for Response Sets, Questions, Forms and Surveys. The button appears if the item is editable: most recent version, user is author and item is draft.
> [SDP-474] Publisher lookup

- .rubocop.yml
- lib/tasks/data.rake
This rake task populates the database with items needed for load testing, as specified in the test plan. Those items include:
* A response set with 30 codes
* A form with 500 questions
Running the rake task will insert these into the database. The task does not check to see if those items exist before putting them in the db.
> Rake task to generate data for load testing

- webpack/components/SearchResult.js
- webpack/containers/DashboardContainer.js
- webpack/containers/Header.js
Changes:
- On the widget the form and survey had the same icon, updated form icon to match the other places in the UI
- The steps for the tutorial weren't updating for the dashboard when using the back button since it was a bit different condition than everywhere else in the app. Made the reasons to update less strict to fix this issue.
- Deleted some deadlinks in one of the header dropdowns before beta release
> A couple quick UI consistency / bug fixes I found when reviewing the app

- webpack/components/SearchResult.js
- webpack/containers/DashboardContainer.js
The Analytics widget
The navigation portion of SearchResult
Skipped the header since it is already a <nav> element
Passing WAVE for the stuff I added
> [SDP-538] Adding navigation roles to some elements

- webpack/components/QuestionForm.js
- webpack/styles/elements/_input.scss
Fixes issue where drop down arrows were not present on select elements in the Question form.
This creates a new style for select elements. The only way to get rid
of rounded corners in Chrome is `-webkit-appearance: none;`.
Unfortunately, that causes Chrome to get rid of the arrows on a select
element. This adds an arrow back in via SVG.
> [SDP-539] Drop down arrows on <select> in Question form

- app/serializers/es_question_serializer.rb
- app/views/response_sets/_response_set.json.jbuilder
- docs/elastic_search_schema.json
- features/edit_forms.feature
- features/manage_response_sets.feature
- features/step_definitions/question_steps.rb
- webpack/components/ResponseSetDetails.js
- webpack/components/SearchResult.js
Displaying Source on RS & Hiding Linked RS on non-choice Questions.
It now hides the Linked response set accordion on non-choice response-type questions and shows the response-type instead. It also shows this info instead of the response-set linkage logic on QuestionItems on the FormEdit page
> [SDP-518,520] Displaying RS Source & Hiding Linked RS

- features/step_definitions/form_steps.rb
- features/step_definitions/question_steps.rb
- features/step_definitions/response_set_steps.rb
- features/step_definitions/survey_steps.rb
- webpack/containers/App.js
- webpack/containers/DashboardContainer.js
- webpack/styles/widgets/_analytics.scss
- webpack/styles/widgets/_recentitems.scss
> [SDP-522,524,536] Compliance navigation

- features/manage_response_sets.feature
- features/step_definitions/common_steps.rb
- webpack/components/ModalDialog.js
Alert modals already had keyboard focus and tabbing around would let you select the thing you want to do. This change enables the escape key to close the alert dialog and adds a role to the element.
> [SDP-541] Alert modal fix

- app/controllers/questions_controller.rb
- app/views/questions/index.json.jbuilder
- test/controllers/questions_controller_test.rb
Previously, hitting the /questions endpoint on the web application would
cause at least one DB query per question returned. This was due to what
was being serialized into JSON. This eliminates some troublesome unused
attributes and uses includes on the initial query to eager load
necessary relationships.
> [SDP-551] Eliminate N+1 queries on the questions endpoint

- features/step_definitions/common_steps.rb
- features/tab_navigation.feature
- webpack/components/DashboardSearch.js
- webpack/components/FormEdit.js
- webpack/components/Notification.js
- webpack/components/NotificationDropdown.js
- webpack/components/ResponseSetDragWidget.js
- webpack/components/SearchResult.js
- webpack/components/SurveyEdit.js
- webpack/components/SurveyFormList.js
- webpack/containers/App.js
- webpack/containers/DashboardContainer.js
- webpack/containers/FormSearchContainer.js
- webpack/containers/FormsEditContainer.js
- webpack/containers/Header.js
- webpack/containers/QuestionSearchContainer.js
- webpack/styles/elements/_buttons.scss
- webpack/styles/navigation/_nav.scss
- webpack/styles/widgets/_recentitems.scss
Basic tabIndex order heiarchy:
1) Skip Navigation
2) Navigation
3) Main Content on Pages where the is something to do before search
4) Search and search filters
5) (5+/undefined) anything that should come after 4 is left as undefined so it takes the normal automatic tab order after items that are declared, this works for items that are search results etc
> [SDP-527,556] Interactive Elements and Tab navigation

- app/controllers/forms_controller.rb
- app/views/forms/_form.json.jbuilder
- app/views/forms/index.json.jbuilder
- package.json
- webpack/components/FormQuestionList.js
- webpack/containers/FormShowContainer.js
- webpack/middleware/parent_from_questions.js
- webpack/middleware/parent_from_response_sets.js
- webpack/middleware/question_types_from_questions.js
- webpack/middleware/questions_from_forms.js
- webpack/middleware/questions_from_response_sets.js
- webpack/middleware/response_sets_from_questions.js
- webpack/middleware/response_types_from_questions.js
- webpack/middleware/store_helper.js
This PR contains several performance fixes:
* Single query to the database for all forms
* Single query to the database for an individual form
* Middleware now queues nested items and dispatches them in a single action
* Avoid unnecessary re-rendering on FormQuestionList
* Removed unnecessary fetches in FormShowContainer
The first two items were implemented by cleaning up the JSON views and doing some eager loading in the controller.
Middleware now dispatches far fewer actions, meaning that mapStateToProps will be called far less, which means far fewer renders from components.
FormQuestionList now tells react when it should be re-rendered.
> [SDP-552] Eliminate N+1 forms queries

- webpack/containers/FormShowContainer.js
Previous code removed the fetching of all response sets. This introduced
an issue when clicking on the linked response set for a question as it
might not be in the store.
This adds back in the fetching of all response sets. It's not the most
performance conscious solution, but it will work for now and will be
addressed at a later date.
> Fix display bug on form show

- test/frontend/components/question_details_test.js
- webpack/components/FormShow.js
- webpack/components/QuestionDetails.js
- webpack/components/QuestionForm.js
- webpack/components/ResponseSetDetails.js
- webpack/components/ResponseSetForm.js
- webpack/components/SearchResult.js
- webpack/components/shared_show/ProgramsAndSystems.js
- webpack/components/surveys/Show.js
- webpack/containers/App.js
- webpack/containers/DashboardContainer.js
- webpack/containers/FormsEditContainer.js
- webpack/containers/Header.js
- webpack/containers/Help.js
- webpack/containers/SurveyEditContainer.js
- webpack/styles/layouts/_showpageheader.scss
- webpack/styles/navigation/_nav.scss
Added a lot of screen reader helper text and aria-labels to better organize items on details pages and dashboard. For details see descriptions of the following SDP items:
SDP-565,566,568,569,570,571
> [SDP-full list below] Screen Reader Helpers on Dash and Details Pages

- webpack/styles/navigation/_nav.scss
Real quick fix to address contrast issue when a nav dropdown is open and then focus is moved to another item.
> [Hotfix] Contrast bug

- webpack/components/FormEdit.js
- webpack/components/SearchResult.js
- webpack/components/SurveyFormList.js
- webpack/containers/QuestionEditContainer.js
Screen reader now reads selected response set on added questions in form edit page.
Buttons for selected questions are now more descriptive for screen reader
- [na] Passed all unit tests using `rails test` with 90%+ coverage
- [na] Passed all cucumber tests using `bundle exec cucumber`
- [na] Passed overcommit hooks, including running all code through Rubocop
> [SDP-574]Form edit screen reader

- webpack/components/DashboardSearch.js
- webpack/components/ModalDialog.js
- webpack/components/QuestionItem.js
- webpack/components/ResponseSetModal.js
- webpack/components/accounts/LogInModal.js
- webpack/components/accounts/ProfileEditor.js
- webpack/containers/CodedSetTableEditContainer.js
- webpack/containers/QuestionModalContainer.js
When modals open, they will now state their title in a screen reader as
opposed to reading all of the text in the modal.
> [SDP-567] Fix modals in screen readers

- features/step_definitions/response_set_steps.rb
- webpack/components/CodedSetTable.js
- webpack/containers/CodedSetTableEditContainer.js
- webpack/containers/Header.js
Addresses two issues:
- some ambiguity with the deletion of rows when navigating tables with a screen reader
- Added th ids as per https://www.w3.org/TR/WCAG20-TECHS/H43.html 
> [SDP-573,534] Table Complaince Fixes

- webpack/components/DashboardSearch.js
- webpack/components/FormEdit.js
Advanced search filter by programs and systems now works in IE (selectedOptions not supported in IE).
- [na] Passed overcommit hooks, including running all code through Rubocop
> [SDP-562]Fixing advanced filtering in IE

- .eslintrc
- app/models/user.rb
- config/routes.rb
- config/webpack.config.js
- webpack/containers/App.js
- webpack/containers/Header.js
Login will now use the React login/account creation if the environment variable OPIDC_HOST isn't set. If it is it will redirect the user to the OPIDC_HOST url to do that workflow. 
Tested by setting the environment variable OPIDC_HOST to "http://localhost:3000" to test that it created a link to that URL. Without that variable set it should run as normal.
> [SDP-523] Make Login configurable

- .github/PULL_REQUEST_TEMPLATE
- webpack/components/NestedSearchBar.js
Added a button to search bar and made it behave the same as other search bars in the app
Also added a line to the PR template to check 508 compliance.
> [SDP] Update RS Search Bar on Question Creation 

- webpack/styles/base/_fonts.scss
Moved Montserrat font to load over HTTPS.
> [SDP 516] External Resources not loaded over HTTPS

- features/export_forms.feature
- features/step_definitions/form_steps.rb
- test/frontend/reducers/test_search_results.js
- webpack/actions/search_results_actions.js
- webpack/components/QuestionItem.js
- webpack/components/ResponseSetDragWidget.js
- webpack/containers/DashboardContainer.js
- webpack/containers/FormSearchContainer.js
- webpack/containers/QuestionSearchContainer.js
- webpack/reducers/search_results_reducer.js
Previously, all fetched search results were stored under a single key in
the redux store. That meant if there were multiple components capable of
search being displayed at the same time, all of their search results
would change in unison. This is not desired, as the components are often
searching for different items, like questions vs. response sets.
This change creates a context for each components' search results. That
way, they don't mess with each other.
This also cleans up some tests, where cucumber steps were written
anticipating the previous behavior.
> [SDP-606] Rework how search results are stored in redux

- app/views/forms/_form.json.jbuilder
- test/frontend/middleware/test_questions_from_search_result.js
- webpack/containers/FormShowContainer.js
- webpack/containers/FormsEditContainer.js
- webpack/middleware/questions_from_search_result.js
- webpack/middleware/response_sets_from_forms.js
- webpack/store/configure_store.js
Removes fetching all questions and fetching all response sets from the form containers. Retrieval of the information is now done through augmenting the individual form object that is returned by fetchForm and middleware to pull the information from the form or search results.
> [SDP-591] Form container cleanup

- features/edit_forms.feature
- features/step_definitions/form_steps.rb
- webpack/components/QuestionItem.js
- webpack/components/SearchResult.js
On form edit page, 'Modify program variable' option in menu for added questions now says 'Add program variable' when there isn't already one in there. Also got rid of some anonymous functions as props to components to maybe improve performance.
> [SDP-616] Changing modify program variable to add program variable 

- webpack/containers/DashboardContainer.js
- webpack/reducers/search_results_reducer.js
Fix bug with load more displaying a page behind and with multiple search requests going out with every search when on the dashboard.
> [SDP-641,643] Multiple search requests

- webpack/components/CodedSetTable.js
- webpack/components/accounts/LogInModal.js
- webpack/containers/CodedSetTableEditContainer.js
- webpack/containers/DashboardContainer.js
- webpack/containers/FormShowContainer.js
- webpack/containers/FormsEditContainer.js
- webpack/containers/Help.js
- webpack/containers/QuestionEditContainer.js
- webpack/containers/QuestionShowContainer.js
- webpack/containers/ResponseSetEditContainer.js
- webpack/containers/ResponseSetShowContainer.js
- webpack/containers/SurveyEditContainer.js
- webpack/containers/surveys/ShowContainer.js
- webpack/styles/navigation/_nav.scss
Addresses the following bugs / updates:
* 610 - Notification of invalid credentials, now uses bootstrap alert to make improper login much more apparent
* 613 - Reorder display name, code, code system column on codedsetedittable, also added interactive help steps to the QuestionEdit and ResponseSetEdit pages to explain what the input columns are for
* 614 - Explain difference between edit and extend - inlining this into the actual step-by-step walkthrough was a bit dense looking so I tried to simplify it in two ways: 1) the first step on all pages now includes a link to the full documentation and says explicitly to look there for more detailed information. 2) The show page interactive tours now include a link to the help documentation and instructions as to what section to look for …
> [SDP-610,613,614,617] Help docs updates

- test/frontend/components/coded_set_table_test.js
- webpack/components/CodedSetTable.js
Noticed a bunch of mismatches in the tests and React props with how the component works in the real world.
> [SDP-615] Sorting code set tables by system, then code

- webpack/components/QuestionForm.js
I was able to reproduce the 626 bug where extension of certain questions wouldn't allow you to add selected RS sets to the right via drag and drop or the button. It took awhile to figure out but the fix is very simple (the selected rs was empty for non choice on extension but the state for extension was storing an undefined when extending into a choice type).
> [SDP-626] Extend bug

- webpack/components/FormShow.js
- webpack/components/QuestionDetails.js
- webpack/components/QuestionWidget.js
- webpack/components/ResponseSetDetails.js
- webpack/components/ResponseSetWidget.js
- webpack/components/surveys/Show.js
Now states that things can't be undone.
Only changes text. No code was harmed in the creation of this PR.
> [SDP-620] Updated prompts when deleting stuff

- app/controllers/forms_controller.rb
- app/models/form.rb
- app/models/form_question.rb
- app/serializers/es_form_serializer.rb
- app/serializers/es_question_serializer.rb
Testing on a 500 question form, reduced save time from 25.5 seconds to 2.3 seconds. Also made the ES serializers for Forms/Questions more efficient so those jobs are easier on the DB.
> [SDP-612] Fix form save performance

- webpack/components/ResponseSetDragWidget.js
Previously, you could only remove the *last* response set that was added
to a question with a type of choice or open choice. This was because
the remove button is an actual button and will cause the question form
to submit when clicked.
This change catches the click event and then calls preventDefault, which
will prevent the form from submitting.
While this fixes the issue, I still have no idea how you could click the
last item in the list with the previous code and not have it submit the
form.
> [SDP-625] Fixing bug w/removing response sets from questions

- webpack/components/QuestionForm.js
Quick fix for bug sometimes not allowing you to add response sets to questions. Check JIRA for gif of how to reproduce / test
> [SDP-645] Bug when trying to add RS after error

- webpack/components/QuestionItem.js
- webpack/containers/FormSearchContainer.js
- webpack/containers/QuestionSearchContainer.js
Simple PR to reduce unnecessary network traffic by limiting searches to only happen when they are necessary on survey and form edit pages. Previously there were double searches firing on both of these pages, and many searches happening as outlined in bug [SDP-644]
> [SDP-644] Extra searches

- lib/tasks/data.rake
Extend the data:load_test task so that it will now also create a survey
that has 500 questions. This is done by creating 5 forms that have 100
questions each.
> [SDP-648] Create 500 question survey for testing

- features/help.feature
- webpack/components/DashboardSearch.js
- webpack/components/QuestionItem.js
- webpack/components/ResponseSetModal.js
- webpack/components/accounts/LogInModal.js
- webpack/components/accounts/ProfileEditor.js
- webpack/containers/App.js
- webpack/containers/CodedSetTableEditContainer.js
- webpack/containers/DashboardContainer.js
- webpack/containers/FormShowContainer.js
- webpack/containers/FormsEditContainer.js
- webpack/containers/Header.js
- webpack/containers/Help.js
- webpack/containers/QuestionEditContainer.js
- webpack/containers/QuestionShowContainer.js
- webpack/containers/ResponseSetEditContainer.js
- webpack/containers/ResponseSetShowContainer.js
- webpack/containers/SurveyEditContainer.js
- webpack/containers/surveys/ShowContainer.js
- webpack/styles/elements/_buttons.scss
First round of 508 feedback changes including:
See story for details, this involved making it so if a type filter is selected the clear type filter link is in the tab order before the my-stuff sidebar
This involved 3 sets of changes to the help page according to the document linked in the story:
- Adding labelledby and aria controls to properly associate things
- Setting up state in the help page to add aria-hidden to things that are not on the page
- Setting up state to dynamic use aria-selected on the two sets of tabs
This issue was addressed in two ways:
1) the actual walkthrough was brought into compliance, enough so that I could write a cucumber test for it and it no longer displayed accessibility audit failures. This included dealing with contrast issues, getting rid of the …
> [SDP 649-653] Feedback 508

- webpack/components/FormEdit.js
- webpack/components/QuestionItem.js
- webpack/containers/FormsEditContainer.js
- webpack/containers/QuestionSearchContainer.js
- webpack/prop-types/response_set_props.js
Reducing the number of unecessary re-renders on the form edit page. 
> [SDP-647]Form edit perf

- package.json
- webpack/components/CodedSetTable.js
- webpack/components/Comment.js
- webpack/components/DashboardSearch.js
- webpack/components/Errors.js
- webpack/components/FormEdit.js
- webpack/components/QuestionDetails.js
- webpack/components/QuestionForm.js
- webpack/components/ResponseSetDetails.js
- webpack/components/SearchResult.js
- webpack/components/accounts/ProfileEditor.js
- webpack/components/shared_show/ProgramsAndSystems.js
- webpack/components/shared_show/PublisherLookUp.js
- webpack/containers/CodedSetTableEditContainer.js
- webpack/containers/DashboardContainer.js
- webpack/containers/FormsEditContainer.js
- webpack/containers/Header.js
- webpack/containers/QuestionModalContainer.js
- webpack/containers/ResponseSetShowContainer.js
- webpack/containers/SurveyEditContainer.js
- webpack/reducers/concept_systems_reducer.js
- webpack/reducers/forms_reducer.js
- webpack/reducers/questions_reducer.js
- webpack/reducers/reducer_generator.js
- webpack/reducers/response_sets_reducer.js
- webpack/reducers/search_results_reducer.js
- webpack/reducers/surveys_reducer.js
- webpack/selectors/response_set_selectors.js
Although I have tagged this with SDP-659, this should improve performance across the application.
Two major changes to reduce the size of the JavaScript that is sent to
the browser. First, instead of including all of lodash, including the
individual functions needed. Next, replacing moment with date-fns.
moment does not play nicely with webpack and includes locale files for
everywhere it supports. Webpack can be configured to ignore these, but
the resulting library is still pretty big. date-fns is significantly
smaller and works well with webpack.
> [SDP-659] Reduce webpack bundle size

- app/views/layouts/application.html.erb
- app/views/layouts/landing.html.erb
- config/webpack.config.js
- package.json
- webpack/application.js
- webpack/landing.js
- webpack/styles/base/_fonts.scss
This is another PR that contains performance improvements for the application that were implemented as I am working on improving survey load.
This removes bootstrap-loader. This package had its own webpack entry point and was loading the JavaScript portions of bootstrap into the application. It was also loading the bootstrap styles. This was redundant as the styles were also being incorporated into the application's scss. This meant that two copies of the bootstrap css styles were being sent to the browser.
Loading of the JavaScript part of bootstrap has been moved to landing.js. References to the bootstrap webpack entry point have been removed.
Removes application.js as it is no longer used.
Removes an unused font.
The application will now launch the webpack bundle analyzer in a browser …
> [SDP-659] More webpack clean up

- app/controllers/api/forms_controller.rb
- app/controllers/api/surveys_controller.rb
- app/controllers/forms_controller.rb
- app/controllers/surveys_controller.rb
- app/jobs/update_index_job.rb
- app/models/form.rb
- app/models/form_question.rb
- app/models/question.rb
- app/models/response_set.rb
- app/models/survey.rb
- app/models/survey_form.rb
- app/serializers/survey_serializer.rb
- lib/sdp/elastic_search.rb
- lib/tasks/data.rake
- test/jobs/update_index_job_test.rb
- test/support/fakeweb.rb
Improved Form save performance , by not returning the whole object in response to a save, and by making ES jobs not immediately serialize the object before putting the job in the queue. Also fixed API survey bug where questions were missing.
> [SDP-660, 668] Form edit performance improvements And API fix

- app/models/form.rb
- app/models/question.rb
- app/models/survey.rb
- config/webpack.config.js
- test/controllers/questions_controller_test.rb
- test/fixtures/questions.yml
- test/models/form_test.rb
- test/models/question_test.rb
- test/models/survey_test.rb
- webpack/components/DashboardSearch.js
- webpack/components/QuestionForm.js
- webpack/containers/DashboardContainer.js
Does the following:
- Makes analyzer plugin not run in production
- Makes it so creating a question and not changing response type behaves as expected / as displayed (saves with first response type in the list instead of as undefined / null)
- Update wording for clearing advanced filters as per a discussion with ammu concerning feedback from UAT
- Adds validation on names for all object creation, will also add validation on response_type for questions once I can figure out issues it causes with redcap import
> [SDP-677,678,679] Question response type default and other bugs

- test/frontend/components/question_form_test.js
I've upgraded to node v8.1.3 and the removed line was causing problems.
I'm not sure how it ever worked, but the QuestionForm component does not
need a show property.
> Removing invalid JS from a test

- lib/tasks/data.rake
Questions now require having a response type. This change ensures that
all questions are now created with a response type by looking up
'Boolean'. It will not exit the rake task if the database has not been
seeded with the response types.
> Fix generation of performance test data

- features/edit_forms.feature
- features/manage_surveys.feature
- webpack/components/SearchResult.js
- webpack/containers/FormSearchContainer.js
- webpack/containers/FormsEditContainer.js
- webpack/containers/QuestionSearchContainer.js
- webpack/containers/SurveyEditContainer.js
When you add a question to a form or form to a survey, the add button becomes a  grey checkmark to let you know it can't be added again.
> [SDP-492] Show added items

- webpack/actions/landing.js
- webpack/actions/types.js
- webpack/components/FormShow.js
- webpack/components/QuestionDetails.js
- webpack/components/ResponseSetDetails.js
- webpack/components/ResponseSetDragWidget.js
- webpack/components/surveys/Show.js
- webpack/containers/DashboardContainer.js
- webpack/containers/FormSearchContainer.js
- webpack/containers/FormShowContainer.js
- webpack/containers/QuestionModalContainer.js
- webpack/containers/QuestionSearchContainer.js
- webpack/containers/QuestionShowContainer.js
- webpack/containers/ResponseSetShowContainer.js
- webpack/containers/surveys/ShowContainer.js
- webpack/reducers/stats.js
If you delete an item the analytics widget and the myStuffCounts now update appropriately before the redirect. This also fixes a one off bug with the load more logic. I tried to also make the delete action remove the deleted item from the store but there is a bit of a race condition in that if the job to remove the item from elastic search isn't completed by the time the redirect to '/' happens the fetch new search results will still return the deleted item.
> [SDP-709,712] Update Analytics when item Deleted

- features/session.feature
- webpack/containers/DashboardContainer.js
This button linked to the sign up form. This is a problem when user
registration is disabled. To fix this, the button was simply removed.
> [SDP-728] Removes the "Get Started!" button

- npm-shrinkwrap.json
- package.json
This PR adds an NPM shrink-wrap file to lock down our versions. Doing this makes builds more reproducible. It does slightly complicate updating and changing, to do so, delete the shrink-wrap file, change you dependency, then run `npm shrinkwrap --dev`
> [SDP-723] Add NPM Shrinkwrap to specify versions

- features/edit_questions.feature
- lib/sdp/simple_search.rb
- webpack/containers/response_sets/ResponseSetDragWidget.js
Now when you select a response set on the question edit page, check marks appear!
> [SDP-745] Adding checkmark to response set search list on question edit page

- test/frontend/components/forms/form_show_test.js
- webpack/components/SearchResult.js
- webpack/components/forms/FormShow.js
- webpack/containers/App.js
- webpack/containers/forms/FormShowContainer.js
- Bug fix on search results imported without createdBy not crashing dashboard.
- Form show container optimization thanks to denormalize use not requiring fetching from store (some changes were made in normalizr branch this improves them)
- Changed the way skip nav works to no longer lock out of navigation, in edge and chrome behaves as desired but in I.E. there is an issue still (skips all tabIndex explicit items unless you shift tab.
> [SDP-740,746,755] Form show normalizr

- webpack/actions/search_results_actions.js
- webpack/components/questions/QuestionEdit.js
- webpack/containers/forms/FormsEditContainer.js
- webpack/containers/questions/QuestionEditContainer.js
- webpack/containers/response_sets/ResponseSetEditContainer.js
Updated the QuestionEdit component so that it will now use questionType and responseType on question as opposed to questionTypeId and responseTypeId. This allowed me to git rid of those in mapStateToProps.
Changed how the payload is provided to ADD_ENTITIES_FULFILLED action from search results. Objects in search results have a codes property, which is different with how they are returned directly from the server. This change brings both payloads in line with each other.
> [SDP-741] Clean up mapStateToProps in QuestionEditContainer

- app/controllers/forms_controller.rb
- app/controllers/questions_controller.rb
- app/controllers/response_sets_controller.rb
- app/controllers/surveys_controller.rb
- app/jobs/delete_from_index_job.rb
- app/models/form.rb
- app/models/question.rb
- app/models/response_set.rb
- app/models/survey.rb
- lib/sdp/elastic_search.rb
- test/controllers/survey_controller_test.rb
- test/jobs/delete_from_index_job_test.rb
Prior to this change, when deleting an item through its controller, a
background job would be created to delete the item from the
elasticsearch index. Dependent relationships would also kick off their
own background jobs to update more in the index.
This change pulls the elasticsearch index delete into the request
response cycle for the controller. Updates to the index for dependent
items still take place in a background job.
> [SDPV-23] Making item delete in elasicsearch blocking

- app/controllers/elasticsearch_controller.rb
- config/routes.rb
- lib/sdp/elastic_search.rb
- lib/sdp/simple_search.rb
- test/controllers/elasticsearch_controller_test.rb
- test/unit/lib/elastic_search_test.rb
- test/unit/lib/simple_search_test.rb
- webpack/_routes.js
This is the Rails side of the duplicate question finder (where you can send the service content and description to see if there are matching questions). Includes elasticsearch implementation and db fallback. Frontend implementation to follow.
> [SDPV-59] Implementation of the duplicate question finder service

- features/step_definitions/common_steps.rb
- features/step_definitions/question_steps.rb
- webpack/components/SearchResult.js
- webpack/styles/layouts/_maincontentarea.scss
- webpack/styles/layouts/_showpageheader.scss
- webpack/styles/widgets/_searchresults.scss
Simple UI update to avoid confusion about what is a link and what isn't
> [SDPV-57] Object names not blue

- lib/sdp/importers/spreadsheet.rb
- test/unit/lib/mmg_test.rb
MMG importer used to have 1-based position. This changes it to be
0-based so that it is aligned with the web application.
> [SDPV-3] Fixing the position of forms and questions

- webpack/components/questions/QuestionEdit.js
- webpack/containers/Header.js
2 changes:
- Fix question potential duplicate suggestions so that when you go to a question edit page after the suggestions have already been made in a previous edit screen, it hides the suggestion UI until the suggestions are updated
- Add a link to help drop down that links to the swagger API
> [SDPV-106,114] Clear suggestions & api link

- app/models/survey.rb
- app/views/surveys/show.json.jbuilder
- test/fixtures/forms.yml
- test/frontend/components/survey/survey_show_test.js
- test/models/survey_test.rb
- webpack/components/SearchResult.js
- webpack/components/surveys/SurveyShow.js
- webpack/styles/master.scss
- webpack/styles/widgets/_surveyform.scss
- webpack/utilities/componentHelpers.js
Following the same pattern for forms and questions, this change now
shows versions of forms that are in a survey and will show when there is
a newer version of the form available.
Passed WAVE
> [SDPV-115] Showing out of date forms on surveys

- app/controllers/surveys_controller.rb
- app/views/surveys/redcap.xml.erb
- config/routes.rb
- test/controllers/survey_controller_test.rb
- n\a If any changes were made to config/routes.rb run `rake jsroutes:generate`
- n\a If any HTML was added or modified check to make sure it was still 508 compliant with WAVE tool / carried over any attributes from similar sections
Adds ability to export a Survey in Redcap xml format.
> [SDPV-98] Redcap surveys

- features/advance_search.feature
- webpack/components/DashboardSearch.js
When you open the advanced search on the dashboard, you can now search for programs and systems to select.
Changes passed WAVE.
> [SDPV-129] Search for prog/sys in advanced search filters

- app/controllers/elasticsearch_controller.rb
- features/advance_search.feature
- lib/sdp/elastic_search.rb
- webpack/actions/search_results_actions.js
- webpack/components/DashboardSearch.js
- webpack/styles/widgets/_search.scss
This does two things to the search results:
- by default the search results with the same score returned from elasticsearch will now be ordered (secondarily by default) by their system usage.
- when the sort filter is specified in the drop down, returned results will be sorted by system usage first and score second.
I did it as a drop down since there are other sort types on the backlog
> [SDPV-65] System use sort

- .eslintrc
- app/controllers/registrations_controller.rb
- app/helpers/application_helper.rb
- app/views/layouts/application.html.erb
- app/views/layouts/landing.html.erb
- config/initializers/devise.rb
- config/settings.yml
- config/webpack/production.js
- config/webpack/shared.js
- features/session.feature
- features/step_definitions/common_steps.rb
- webpack/containers/App.js
- webpack/containers/Header.js
This PR addresses issues related to disabling the user registration features of the application and makes configuration of this feature a runtime configuration setting and not an asset compilation time setting. 
> Disable user registration

- Jenkinsfile
This reflects a move to the new CI/CD pipeline process we are putting in place.
- [ NA ] Added unit tests for new functionality
- [ NA ] Passed all unit tests using `rails test` with 90%+ coverage
- [ NA ] Added cucumber tests for any new functionality
- [ x ] Passed all cucumber tests using `bundle exec cucumber`
- [ x ] Passed overcommit hooks, including running all code through Rubocop
- [ NA ] If any database changes were made, run `rake generate_erd` to update the README.md
- [ NA ] If any changes were made to config/routes.rb run `rake jsroutes:generate`
- [ NA ] If any HTML was added or modified check to make sure it was still 508 compliant with WAVE tool / carried over any attributes from similar sections
> Changing style of Jenkins Pipeline for CI/CD process

- webpack/components/FHIRDoc.js
- webpack/containers/App.js
- webpack/containers/Header.js
- webpack/landing.js
No new functionality, just documentation.
Documentation page passed WAVE accessibility check.
> [SDPV-290] Adding documentation of the FHIR API

- config/settings.yml
We should not be including MITRE-internal URLs in config files.
- [N/A] Passed all unit tests using `rails test` with 90%+ coverage
- [N/A] If any HTML was added or modified check to make sure it was still 508 compliant with WAVE tool / carried over any attributes from similar sections
> [SDPV-346] Don't have MITRE URLs in config files

- Jenkinsfile
This change just increases the wait time for the openshift SDP-V container build to finish.  It takes longer to complete the build in the CDC environment then in our cluster.
- [N/A] Passed all unit tests using `rails test` with 90%+ coverage
- [N/A] Passed overcommit hooks, including running all code through Rubocop
- [N/A] If any HTML was added or modified check to make sure it was still 508 compliant with WAVE tool / carried over any attributes from …
> [SDPV-366] Increase waitTime for OpenShift build

- Jenkinsfile
Added hooks for updating Slack on new jobs. This currently prints to the platform channel, which we will change to the project channel after testing it with enough jobs.
> Slack integration

- app/controllers/questions_controller.rb
- app/controllers/response_sets_controller.rb
- app/controllers/sections_controller.rb
- app/controllers/surveys_controller.rb
- app/models/concerns/groupable.rb
- app/models/concerns/versionable.rb
- app/models/import_session.rb
- app/models/question.rb
- app/models/response_set.rb
- app/models/section.rb
- app/models/section_nested_item.rb
- app/models/survey.rb
- app/views/questions/_question.json.jbuilder
- db/seeds.rb
- features/edit_questions.feature
- features/widget.feature
- test/controllers/sections_controller_test.rb
- test/controllers/survey_controller_test.rb
- test/models/import_session_test.rb
- webpack/components/SearchResult.js
- webpack/components/questions/QuestionShow.js
- webpack/components/shared_show/ProgramsAndSystems.js
- webpack/containers/surveys/SurveyImportContainer.js
For the solution to adding a category one was added to seeds file and I will be running the same command in Prod and Demo (as soon as I get my badge).
Fixes include:
- Cascading delete for draft content that is only used on the survey / section / question being deleted
- Workin ES updates for response_sets (was dropping underscore in places)
- Properly cascading delete and group additions
- No more hanging import when mmg is problematic and can't be imported
- Improved error messaging
- ES updates on delete now cascade instead of just parent object updating
- Improved language clarifying association of linked response sets on question show page
Make sure you have checked off the following before …
> Patch to 1.7 - Various bug fixes and minor improvements

- config/environments/test.rb
Theory is that threading issues with ActiveJob are causing the problem.
This change forces the jobs inline, so everything should be single
threaded.
You can find greater detail in my comment here: https://publichealthsurveillance.atlassian.net/secure/RapidBoard.jspa?rapidView=6&projectKey=SDPV&modal=detail&selectedIssue=SDPV-479&quickFilter=11
> [SDPV-479] Possible fix for intermittent test failures

- app/helpers/api/fhir/questionaires_helper.rb
- app/views/api/fhir/questionaires/_question.json.jbuilder
- test/controllers/api/fhir/questionaires_controller_test.rb
- test/fixtures/concepts.yml
Perviously, we were using the question id as the linkId. Now, if the
question is tagged with a Data Element Identifier, that will now be used
as the linkId.
Some minor issues with this change:
* The linkId does not have a place for a code system. Some data element identifiers, but not all, have a code system. In this case it is just dropped.
* The data element identifier is still put in the extensions. I can filter it out if we think it is the right thing to do, but I left it, in case someone wanted to look for the code system.
> [SDPV-427] Moving data element id to linkId

- app/controllers/surveys_controller.rb
- app/models/question.rb
- app/models/response_set.rb
- app/models/section.rb
- app/models/survey.rb
- lib/sdp/elastic_search.rb
- test/elastic_helpers.rb
- test/unit/lib/elastic_search_test.rb
This change cut the response time of the duplicates endpoint on surveys from 13 seconds on my laptop for the Hepatitis MMG to about 5 seconds.
It eliminates the use of `q_with_dupes_count` which is where most of the savings comes from. It also uses batching to send all elastic search queries for a section at once.
Finally, it fixes an unrelated bug. The surveys controller would crash if you went to it directly upon server start in development mode. This is because the SDP::Elasticsearch library wasn't loaded yet, but it typically is somewhere in the flow of the dashboard controller, which is why this probably went unnoticed.
> [SDPV-495] Reduce load time of duplicates in the curation page

- config/settings.yml
- lib/tasks/elasticsearch.rake
- webpack/components/FHIRDoc.js
Now mentions that we are putting the Data Element Identifier in
Question.item.linkId.
> [SDPV-525] Updating docs on the FHIR API

- app/models/response_type.rb
- lib/sdp/importers/spreadsheet.rb
- test/controllers/categories_controller_test.rb
- test/fixtures/categories.yml
- test/fixtures/questions.yml
- test/fixtures/response_types.yml
- test/fixtures/subcategories.yml
This commit brings the test fixtures in line with the database seed
file.
It also adds the string response type to the spreadsheet importer. It's
possible to add more types, we just need to figure out what they are
called in the MMG files.
> [SDPV-526, 542] Updating fixtures, fixing import response type

- features/manage_response_sets.feature
- features/step_definitions/response_set_steps.rb
- webpack/components/SearchResult.js
- webpack/styles/layouts/_panels.scss
Fix for SDPV-318 : UI: Display "Source" on Response Set Summary
Search widget result source should show "Local" for locally created response set, or have the same link to PHIN VADS if the imported response set includes a PHIN VADS oid.
> Response Set source

- Gemfile.lock
- db/migrate/20180925164840_add_associations_to_versions.rb
Adjusting migration so HStore needs to be manually enabled (since it can't be enabled from vocab container in cluster via migrations)
> [SDPV-676] Migrate fix 1 13

- Jenkinsfile
- features/support/env.rb
- test/elastic_helpers.rb
1) We don't need to create the test database.  The database is already
created as part of the container initialization.
2) Added .sdp.svc to NO_PROXY env var to run tests.  This isn't
necessary in the CDC environment, but in the MITRE env, this prevents
requests for the concept-manager service from being sent to the MITRE
proxy server, which responds with a 503 error.
3) Corrected uri registered with FakeWeb for concept-manager svc
4 ) Removed call to FakeWeb.clean_registry
> [SDPV-767] Fixing issues with tests in the CDC Dev/Test env

- .rubocop.yml
- Gemfile
- Gemfile.lock
- Jenkinsfile
- Rakefile
- lib/tasks/cucumber.rake
This change will publish the Brakeman, Cucumber, and RuboCop test results back to Jenkins so that they are more easily viewed as part of each build rather than the raw console log output.
> [SDPV-743] Publish test results

- Jenkinsfile
Just increased scan timeout to 60 minutes to prevent timing out in the CDC environment.
> Increased Twistlock scan and publish timeout

- docs/elastic_search_schema.json
- lib/sdp/elastic_search.rb
- webpack/components/surveys/SurveyDedupe.js
Change Include:
- removing irrelevant match attributes for this type of mathcing
- upping the match threshold to require more accurate matches
- using the new tokenizers for fields
- displaying the fields that matched above the threshold at the bottom of each result
- making the result fuzzy again
- some advanced stuff I read up on with having attribute vectors indexed with offsets so it improves accuracy at the cost of minor speed (tested and not a noticable difference) and space. This also will allow highlighting / display of all matched fields and the text they matched on easily if we want to add highlighting all the matched attributes
Make sure you have checked off the following before you …
> [SDPV-637] Optimize curation wizard match

- config/environments/production.rb
This change bumps up the logging level from warn to info so that we get the rails route information in the log files.
> Changed production config to log at info level

- Jenkinsfile
I deliberately left the message contents redundant (instead of making them a single constant value) so that they can be fine-tuned to include whatever information their recipients (most likely @ttaylor249) 
desire in the future.
> Send emails after attempted dev environment build
