CDCgov/SDP-Vocabulary-Service

- app/controllers/questions_controller.rb
- app/views/layouts/application.html.erb
- app/views/questions/show.html.erb
- config/database.yml
- db/migrate/20161006151401_remove_response_set_string_from_questions.rb
- db/schema.rb
- db/seeds.rb
Removed the unnecessary string column that was causing update issues and stripped out it's use - also, made minor changes to prep for concept authoring and fixed a minor typo in db template.
NOTE: After this migration sqlite will not work because of remove_column method
> Questions Model Debugging

- app/assets/javascripts/concepts.coffee
- app/assets/stylesheets/concepts.scss
- app/controllers/concepts_controller.rb
- app/helpers/concepts_helper.rb
- app/models/concept.rb
- app/views/concepts/_concept.json.jbuilder
- app/views/concepts/_form.html.erb
- app/views/concepts/edit.html.erb
- app/views/concepts/index.html.erb
- app/views/concepts/index.json.jbuilder
- app/views/concepts/new.html.erb
- app/views/concepts/show.html.erb
- app/views/concepts/show.json.jbuilder
- app/views/layouts/application.html.erb
- config/routes.rb
- db/migrate/20161006225701_create_concepts.rb
- db/schema.rb
- db/seeds.rb
- test/controllers/concepts_controller_test.rb
- test/fixtures/concepts.yml
- test/models/concept_test.rb
Also fixed rubocop issues and got my overcommit working - I will adjust commit msg warnings in future.
> added basic concept scaffold for author and updated interface accordingly

- app/controllers/question_types_controller.rb
- app/controllers/questions_controller.rb
- app/models/question.rb
- app/models/question_type.rb
- app/models/response_set.rb
- app/views/layouts/application.html.erb
- app/views/question_types/_form.html.erb
- app/views/question_types/_question_type.json.jbuilder
- app/views/question_types/edit.html.erb
- app/views/question_types/index.html.erb
- app/views/question_types/index.json.jbuilder
- app/views/question_types/new.html.erb
- app/views/question_types/show.html.erb
- app/views/question_types/show.json.jbuilder
- app/views/questions/_form.html.erb
- app/views/questions/_question.json.jbuilder
- app/views/questions/index.html.erb
- app/views/questions/show.html.erb
- config/routes.rb
- db/migrate/20161010142315_create_question_types.rb
- db/migrate/20161011152231_add_question_type_to_question.rb
- db/schema.rb
- test/controllers/question_types_controller_test.rb
- test/controllers/questions_controller_test.rb
- test/fixtures/question_types.yml
- test/fixtures/questions.yml
- test/fixtures/questions.yml.orig
- test/models/question_test.rb
- test/models/question_type_test.rb
- Build QuestionModel migrations and views
- Add in code for supporting QuestionType on the Question model
- Build supporting tests for QuestionType (model and controller)
- Build supporting tests for Question (model and controller) dealing with QuestionType
- Fix failing fk test by adding `dependent: :nullify` to the `response_set` model
- Replace hand built links in navigation with rails helper links
- Make links in nav bar display active only when they were in fact active
> Question Type CRUD Operations (SDP-103 and SDP-76)

- app/controllers/concepts_controller.rb
- app/models/concept.rb
- app/models/response_set.rb
- app/views/concepts/_form.html.erb
- app/views/concepts/index.html.erb
- app/views/concepts/show.html.erb
- db/migrate/20161012094724_create_concepts_response_sets.rb
- db/schema.rb
Using the Has and Belongs to Many helper I created a join table between concepts and response sets and added functionality for demoing on creation of a concept you can link multiple response sets and have them display in the UI.
> Concepts linking

- Procfile
- app/views/concepts/_form.html.erb
- app/views/concepts/index.html.erb
- app/views/question_types/index.html.erb
- app/views/questions/index.html.erb
- app/views/response_sets/index.html.erb
- app/views/responses/index.html.erb
- features/manage_concepts.feature
- features/manage_question_types.feature
- features/manage_questions.feature
- features/manage_response_sets.feature
- features/manage_responses.feature
- features/session.feature
- features/step_definitions/common_steps.rb
- features/step_definitions/concept_steps.rb
- features/step_definitions/question_steps.rb
- features/step_definitions/question_type_steps.rb
- features/step_definitions/response_set_steps.rb
- features/step_definitions/response_steps.rb
- features/step_definitions/session_steps.rb
- features/support/env.rb
- features/support/warden.rb
- test/test_helper.rb
- webpack/application.js
Make sure to run foreman start before running cucumber
> Cucumber tests

- app/views/devise/registrations/edit.html.erb
- features/session.feature
replace bootstrap_form_for with normal form_for due to changes in how we handle css. Added test to ensure we don't break this page in the future
> Fix Broken Profile Page

- app/views/layouts/application.html.erb
- webpack/styles/elements/_footer.scss
- webpack/styles/elements/_header.scss
- webpack/styles/elements/_variables.scss
- webpack/styles/scaffolds.scss
Adds fonts, colors, navbar, and footer
> Add rough styling 

- .brakeman.yml
- .gitignore
- Gemfile
- Gemfile.lock
- Rakefile
- config/cucumber.yml
- features/step_definitions/session_steps.rb
- lib/tasks/admin.rake
- lib/tasks/audit.rake
- lib/tasks/brakeman.rake
- lib/tasks/cucumber.rake
- test/support/capybara.rb
- test/support/mailer.rb
- test/support/rails.rb
- test/support/reporters.rb
- test/support/simplecov.rb
- test/test_helper.rb
This PR adds the functionality to run all of the test reports and archive their results in a single directory, reports.   There is the limitation in that if a single test suite fails it will not continue with the rest of the suites.  But as this is to facilitate the dev ops chain I think that is ok because we can still run the tests individually on the development machines
> Test reports

- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/layouts/application.html.erb
- webpack/styles/layouts/_body.scss
Updating the default devise login forms with simple bootstrap layout and classes.  This is purely a styling change.
- N/A Added cucumber tests for any new functionality
> Update devise forms

- test/frontend/components/question_list_test.js
- test/frontend/components/question_widget_test.js
- test/frontend/mock_routes.js
- webpack/components/QuestionList.js
- webpack/components/QuestionWidget.js
- webpack/question_list.js
- N/A Added unit tests for new functionality - no new functionality
- N/A Added cucumber tests for any new functionality - no new functionality
Removed unnecessary constructors
Now accessing route helpers as React props
Simplified test code since it doesn't need access to the component
instance
Reformatted JSX to 2 space indenting
> Refactored the QuestionList component

- app/views/forms/_form.html.erb
- app/views/questions/new.html.erb
- app/views/questions/revise.html.erb
- package.json
- webpack/components/QuestionWidget.js
- webpack/components/ResponseSetWidget.js
- webpack/styles/base/_variables.scss
- webpack/styles/scaffolds.scss
- n/a Added unit tests for new functionality
> changing over to use font-awesome

- app/controllers/dashboard_controller.rb
- app/helpers/dashboard_helper.rb
- app/views/dashboard/index.html.erb
- app/views/questions/index.html.erb
- config/routes.rb
- test/controllers/dashboard_controller_test.rb
- webpack/styles/base/_colors.scss
- webpack/styles/navigation/_nav.scss
- webpack/styles/widgets/_analytics.scss
Added the dashboard controller to start adding in widgets for testing - put in some placeholder divs and css necessary to build.
After this is merged I will rebase and integrate the Search widget which uses the question and response set widgets, this is just the baseline, not all of the css from eny's WIP branch was added.
> Added dashboard controller

- app/models/form.rb
- test/fixtures/forms.yml
- test/models/form_test.rb
- N/A Added cucumber tests for any new functionality
> Ensures that no two forms have the same OMB number [SDP-243]

- app/controllers/forms_controller.rb
- app/views/forms/index.html.erb
- config/webpack.config.js
- features/manage_forms.feature
- features/step_definitions/common_steps.rb
- features/step_definitions/form_steps.rb
- test/frontend/components/form_list_test.js
- test/frontend/components/form_widget_test.js
- test/frontend/mock_routes.js
- webpack/_routes.js
- webpack/components/FormList.js
- webpack/components/FormWidget.js
- webpack/form_list.js
- webpack/styles/master.scss
- webpack/styles/widgets/_forms.scss
> Form widget, associated mocha and cucumber tests

- app/controllers/comments_controller.rb
- config/application.rb
- config/settings/development.yml
- config/settings/production.yml
- config/settings/test.yml
- lib/sdp/comments_notifier.rb
- test/unit/lib/comments_notifier_test.rb
> Comment notifications

- app/controllers/notifications_controller.rb
- config/routes.rb
- test/controllers/notifications_controller_test.rb
- webpack/_routes.js
> Notifications controller

- db/schema.rb
- features/manage_forms.feature
- features/step_definitions/form_steps.rb
- webpack/actions/question.js
- webpack/actions/types.js
- webpack/components/QuestionItem.js
- webpack/containers/FormsQuestionList.js
- webpack/reducers/questions.js
> Sorted form questions

- webpack/components/Header.js
- webpack/containers/App.js
- webpack/styles/layouts/_body.scss
Moves main content down so container development doesn't need to worry about it and just has a div in the right place to work in.
> Add container around content 

- app/controllers/api/forms_controller.rb
- app/controllers/api/questions_controller.rb
- app/controllers/api/response_sets_controller.rb
- app/models/concerns/versionable.rb
- app/serializers/form_serializer.rb
- app/serializers/questions_serializer.rb
- app/serializers/value_sets_serializer.rb
- public/api/vocab.yaml
- test/controllers/api/forms_controller_test.rb
- test/controllers/api/questions_controller_test.rb
- test/controllers/api/response_sets_controller_test.rb
- test/fixtures/responses.yml
- test/support/schemas/forms/show.json
- test/support/schemas/questions/show.json
- test/support/schemas/result_sets/show.json
> Api versioning [SDP-290]

- app/views/forms/_form.json.jbuilder
- webpack/components/FormEdit.js
> Added OMB Approval Number

- app/controllers/questions_controller.rb
- features/manage_forms.feature
- features/manage_questions.feature
- features/manage_response_sets.feature
- test/controllers/questions_controller_test.rb
- webpack/components/QuestionForm.js
- webpack/components/QuestionWidget.js
- webpack/containers/QuestionIndexContainer.js
- webpack/containers/ResponseSetsContainer.js
This PR cleans up some bugs in the application as well as brings some of the cucumber tests in line with the react application
> Small fixes to for cucumber tests and bugs in the app

- app/models/concerns/oid_generator.rb
- test/frontend/components/form_edit_test.js
- test/frontend/components/response_set_form_test.js
- test/frontend/containers/question_edit_container_test.js
- test/frontend/mock_router.js
- test/frontend/mock_routes.js
- webpack/components/FormEdit.js
- webpack/components/QuestionForm.js
- webpack/components/QuestionItem.js
- webpack/components/ResponseSetForm.js
- webpack/containers/FormsEditContainer.js
- webpack/containers/QuestionEditContainer.js
- webpack/containers/ResponseSetEditContainer.js
And bonus infinite loop oid fix.
- na Passed all cucumber tests using `bundle exec cucumber`
> [SDP-305]Warning user from abandoning unsaved changes

- features/manage_questions.feature
- test/frontend/components/errors_test.js
- webpack/actions/questions_actions.js
- webpack/components/Comment.js
- webpack/components/CommentForm.js
- webpack/components/Errors.js
- webpack/components/QuestionForm.js
Note, this also includes [SDP-326] because I was working on the same branch originally. If you accept #115 before this one, it will sort things out, or you can accept this one and get both.
> [SDP-328] Properly handle errors when questions are submitted

- features/manage_forms.feature
- features/manage_response_sets.feature
- webpack/components/FormEdit.js
- webpack/components/QuestionForm.js
- webpack/components/ResponseSetForm.js
Added to response sets and forms
> [SDP-327] Improve save dialog

- app/views/forms/_form.json.jbuilder
- test/frontend/components/version_info_test.js
- webpack/components/FormList.js
- webpack/components/FormShow.js
- webpack/components/VersionInfo.js
- webpack/containers/FormShowContainer.js
- webpack/styles/base/_colors.scss
- webpack/styles/elements/_buttons.scss
- webpack/styles/layouts/_contentbox.scss
- webpack/styles/layouts/_maincontentarea.scss
- webpack/styles/layouts/_printview.scss
- webpack/styles/layouts/_showpageheader.scss
- webpack/styles/master.scss
- webpack/styles/navigation/_sidenav.scss
- webpack/styles/widgets/_forms.scss
- [n/a] Passed all cucumber tests using `bundle exec cucumber`
> [SDP-332] Restyle form show page 

- Gemfile
- Rakefile
- lib/tasks/audit.rake
- lib/tasks/brakeman.rake
- n/a Added unit tests for new functionality
- n/a Passed all cucumber tests using `bundle exec cucumber`
> Deployment fixes

- features/manage_response_sets.feature
- test/frontend/middleware/test_parent_from_response_sets.js
- webpack/components/FormShow.js
- webpack/components/ResponseSetDetails.js
- webpack/containers/DashboardContainer.js
- webpack/containers/FormShowContainer.js
- webpack/containers/ResponseSetShowContainer.js
- webpack/middleware/parent_from_response_sets.js
> [SDP-336] Restyle Response Set Show

- features/manage_questions.feature
- test/frontend/components/question_details_test.js
- test/frontend/containers/question_show_container_test.js
- webpack/components/FormShow.js
- webpack/components/QuestionDetails.js
- webpack/components/ResponseSetDetails.js
- webpack/containers/QuestionShowContainer.js
> [SDP-347] Restyle question show

- db/seeds.rb
- features/manage_forms.feature
- test/frontend/components/form_widget_test.js
- webpack/components/FormList.js
- webpack/components/FormWidget.js
- webpack/containers/FormsIndexContainer.js
- webpack/styles/widgets/_forms.scss
As in didn't break any that were related to style changes -- others are broken do to other circumstances
> Form list rows

- features/manage_questions.feature
- features/manage_response_sets.feature
- features/step_definitions/question_steps.rb
- features/step_definitions/response_set_steps.rb
- webpack/components/CodedSetTable.js
- webpack/components/QuestionDetails.js
- webpack/components/QuestionForm.js
- webpack/components/ResponseSetDetails.js
- webpack/components/ResponseSetForm.js
- webpack/containers/CodedSetTableEditContainer.js
> [SDP-307,SDP-308]Concept service lookup

- app/controllers/forms_controller.rb
- features/manage_forms.feature
- features/manage_notifications.feature
- features/manage_questions.feature
- features/manage_response_sets.feature
- features/step_definitions/form_steps.rb
- features/support/env.rb
- webpack/components/FormWidget.js
- webpack/containers/DashboardContainer.js
- webpack/containers/FormsIndexContainer.js
- webpack/containers/QuestionIndexContainer.js
- webpack/containers/ResponseSetsContainer.js
- webpack/styles/layouts/_panels.scss
There was no JIRA issue for this - minor cleanup of some of the HTML based on changes Eny and I made last week with the show pages. Updated Cucumber tests, only failing test should be:
```bash
cucumber features/manage_forms.feature:105 # Scenario: An invalid control number should not allow save
```
which should be solved as part of [SDP-325]
- [almost] Passed all cucumber tests using `bundle exec cucumber`
> [SDP-325] Search test cleanup

- test/controllers/api/questions_controller_test.rb
- test/controllers/api/response_sets_controller_test.rb
- test/controllers/comments_controller_test.rb
- test/controllers/concepts_controller_test.rb
- test/controllers/forms_controller_test.rb
- test/controllers/questions_controller_test.rb
- test/controllers/response_sets_controller_test.rb
- test/fixtures/questions.yml
- test/models/comment_test.rb
- test/models/form_test.rb
- test/models/notification_test.rb
- test/models/question_test.rb
- test/models/response_set_test.rb
- test/unit/lib/comments_notifier_test.rb
- test/unit/lib/redcap_test.rb
Making rails tests more resilient so they don't break when new fixtures are added
- na Added unit tests for new functionality
- na Passed all cucumber tests using `bundle exec cucumber`
> [SDP-350] Rails unit tests improvements

- features/cancel_buttons.feature
- features/step_definitions/draft_steps.rb
- webpack/components/FormEdit.js
- webpack/components/QuestionForm.js
- webpack/components/ResponseSetForm.js
> [SDP-348] Cancel buttons

- webpack/components/FormShow.js
- webpack/components/FormWidget.js
- webpack/components/QuestionDetails.js
- webpack/components/QuestionForm.js
- webpack/components/QuestionWidget.js
- webpack/components/ResponseSetDetails.js
- webpack/containers/FormsIndexContainer.js
This PR has merged in #144 so that the cucumber tests all passed. That should be merged first.
> [SDP-351] Replace navigational anchor tags with React Link tags

- webpack/components/QuestionForm.js
> Fix failing test that was introduced in #145

- app/controllers/response_sets_controller.rb
- app/models/response_set.rb
- config/routes.rb
- test/controllers/response_sets_controller_test.rb
- test/models/response_set_test.rb
- webpack/_routes.js
> [SDP-276] Rails portion of Response Set versioning

- Jenkinsfile
Broken tests are still broken.  I just fixed the pipeline definition so that Jenkins is running all the stages again.
- [ NA ] Added unit tests for new functionality
- [ NA ] Passed all unit tests using `rails test` with 90%+ coverage
- [ NA ] Added cucumber tests for any new functionality
- [ NA ] Passed all cucumber tests using `bundle exec cucumber`
- [ NA ] Passed overcommit hooks, including running all code through Rubocop
- [ NA ] If any database changes were made, run `rake generate_erd` to update the README.md
- [ NA ] If any changes were made to config/routes.rb run `rake jsroutes:generate`
> [SDP-397] Fixed Jenkinsfile pipeline definition

- .rubocop.yml
- app/controllers/forms_controller.rb
- app/controllers/questions_controller.rb
- app/controllers/response_sets_controller.rb
- app/models/form.rb
- features/manage_forms.feature
- features/manage_questions.feature
- features/manage_response_sets.feature
- features/step_definitions/draft_steps.rb
- test/controllers/forms_controller_test.rb
- test/controllers/questions_controller_test.rb
- test/controllers/response_sets_controller_test.rb
> [SDP-354] Version un-posting

- features/manage_forms.feature
- features/step_definitions/common_steps.rb
- webpack/components/FormEdit.js
- webpack/components/QuestionForm.js
- webpack/components/QuestionResults.js
- webpack/components/ResponseSetDragWidget.js
- webpack/containers/FormsEditContainer.js
- webpack/containers/QuestionModalContainer.js
Updating question create modal to match question edit behavior, and add question you create to the form automatically
> [SDP-365]Updating question create modal

- features/manage_forms.feature
- features/step_definitions/form_steps.rb
- webpack/components/FormEdit.js
- webpack/components/QuestionItem.js
- webpack/components/QuestionResults.js
- webpack/containers/FormsEditContainer.js
> [SDP-334] Form Edit UI improvements

- app/controllers/surveys_controller.rb
- app/models/survey.rb
- app/views/surveys/_survey.json.jbuilder
- app/views/surveys/index.json.jbuilder
- app/views/surveys/show.json.jbuilder
- config/routes.rb
- test/controllers/survey_controller_test.rb
- webpack/_routes.js
> [SDP-236] [SDP-415] Survey controllers and routes

- app/models/form.rb
- app/models/form_question.rb
- app/models/survey.rb
- app/models/survey_form.rb
- app/serializers/es_survey_serializer.rb
- docs/elastic_search_schema.json
- lib/sdp/simple_search.rb
- test/controllers/forms_controller_test.rb
- test/controllers/survey_controller_test.rb
- test/fixtures/surveys.yml
- test/unit/lib/simple_search_test.rb
> Adding Survey to elastic search and updating simple search 

- app/controllers/application_controller.rb
- app/controllers/forms_controller.rb
- app/controllers/registrations_controller.rb
- app/models/form.rb
- app/models/user.rb
- app/serializers/user_serializer.rb
- features/session.feature
- features/step_definitions/session_steps.rb
- features/step_definitions/surveillance_program_steps.rb
- features/step_definitions/surveillance_system_steps.rb
- test/controllers/forms_controller_test.rb
- test/fixtures/surveillance_programs.yml
- test/fixtures/surveillance_systems.yml
- test/fixtures/users.yml
- webpack/components/accounts/SettingsModal.js
- webpack/components/accounts/SignUpModal.js
- webpack/containers/App.js
- webpack/prop-types/current_user_props.js
- webpack/prop-types/surveillance_program_props.js
- webpack/prop-types/surveillance_system_props.js
Now users choose a system and program when they register. They can change them in settings. Also, when creating or updating a form it associates it with the program and system for the current_user. 
> [SPD-413] Associating programs and systems

- app/controllers/elasticsearch_controller.rb
- lib/sdp/elastic_search.rb
- lib/sdp/simple_search.rb
- test/controllers/elasticsearch_controller_test.rb
- test/unit/lib/simple_search_test.rb
> SDP-421 Simple search integration

- features/manage_forms.feature
- features/step_definitions/common_steps.rb
- features/step_definitions/form_steps.rb
- test/frontend/middleware/test_questions_from_response_sets.js
- webpack/components/FormEdit.js
- webpack/components/QuestionItem.js
- webpack/components/QuestionResults.js
- webpack/components/SearchResult.js
- webpack/components/SearchResultList.js
- webpack/containers/FormsEditContainer.js
- webpack/containers/FormsQuestionList.js
- webpack/middleware/questions_from_response_sets.js
- webpack/middleware/response_sets_from_questions.js
- webpack/styles/layouts/_form_edit.scss
Had to comment out a bug caused by middleware that was very hard to figure out. I suggest we refactor the 'QuestionItem' and FormEdit as a whole in the refactor/cleanup sprint as some of the components nested in odd ways. I tried to cleanup QuestionItem a bit while I was working on this at least.
> [SDP-391] Improve RS association on form builder

- app/controllers/surveys_controller.rb
- app/models/survey.rb
- test/controllers/survey_controller_test.rb
- test/fixtures/surveys.yml
> [SDP-429] Survey draft

- features/session.feature
- webpack/containers/AuthenticatedRoutes.js
- webpack/landing.js
> [SDP 401] Create Unauthorized Page

- app/views/surveys/_survey.json.jbuilder
- features/manage_surveys.feature
- features/step_definitions/common_steps.rb
- test/controllers/survey_controller_test.rb
- webpack/components/surveys/Show.js
- webpack/containers/surveys/ShowContainer.js
Displays the surveillance system and program associated with a survey on the show page.
> [SDP-413] Display program and system on survey

- app/controllers/forms_controller.rb
- app/controllers/landing_controller.rb
- app/controllers/questions_controller.rb
- app/controllers/response_sets_controller.rb
- app/controllers/surveys_controller.rb
- features/manage_surveys.feature
- features/step_definitions/survey_steps.rb
- webpack/components/SearchResult.js
- webpack/components/SearchResultList.js
- webpack/components/SurveyEdit.js
- webpack/components/SurveyFormList.js
- webpack/containers/FormSearchContainer.js
Breaking the survey and form edit pages up for easier merging / review on day one of mergapalooza. Also having this logic in helps with the other half of this as well as another story (and the form edit stuff is being edited by someone else so to ease rebasing I thought it best to break that off separately.
> [SDP-443] Elasticsearch on Survey edit pages

- features/manage_questions.feature
- webpack/components/QuestionDetails.js
- webpack/components/QuestionForm.js
> [SDP-389] Concept clarification

- features/edit_forms.feature
- features/export_forms.feature
- features/step_definitions/common_steps.rb
- features/step_definitions/form_steps.rb
- webpack/components/QuestionItem.js
- webpack/components/SearchResult.js
- webpack/containers/FormsEditContainer.js
- webpack/containers/QuestionSearchContainer.js
Added updated widget and updated search with ES and load more to the form editing page. Had to re-write some cukes tests in different ways to deal with ambiguity due to multiple ES searches (one in the modal one on the page).
> [SDP-470] Elastic Search on form edit

- test/frontend/components/form_edit_test.js
- test/frontend/components/form_question_list_test.js
- test/frontend/components/question_form_test.js
- test/frontend/components/response_set_drag_widget_test.js
- test/frontend/components/response_set_form_test.js
- test/frontend/components/survey/show_test.js
- test/frontend/components/survey_edit_test.js
- test/frontend/containers/form_question_list_test.js
- test/frontend/containers/question_edit_container_test.js
- test/frontend/containers/question_new_modal_container_test.js
- webpack/components/FormEdit.js
- webpack/components/QuestionItem.js
- webpack/components/surveys/Show.js
- webpack/containers/FormsQuestionList.js
> [SDP-450] PropType fixes

- app/controllers/api/forms_controller.rb
- app/controllers/api/programs_controller.rb
- app/controllers/api/questions_controller.rb
- app/controllers/api/response_sets_controller.rb
- app/controllers/api/surveys_controller.rb
- app/controllers/api/systems_controller.rb
- app/serializers/program_serializer.rb
- app/serializers/survey_serializer.rb
- app/serializers/system_serializer.rb
- config/routes.rb
- public/api/vocab.yaml
- test/controllers/api/forms_controller_test.rb
- test/controllers/api/programs_controller_test.rb
- test/controllers/api/questions_controller_test.rb
- test/controllers/api/response_sets_controller_test.rb
- test/controllers/api/surveys_controller_test.rb
- test/controllers/api/systems_controller_test.rb
- test/fixtures/surveys.yml
- test/support/schemas/programs/show.json
- test/support/schemas/surveys/show.json
- test/support/schemas/systems/show.json
- webpack/_routes.js
> [SDP-439] Api latest models

- app/controllers/questions_controller.rb
- app/controllers/response_sets_controller.rb
- features/manage_questions.feature
- features/step_definitions/question_steps.rb
- test/controllers/questions_controller_test.rb
> [SDP-399/SDP-400] Additional testing around not logged in users

- app/serializers/survey_serializer.rb
> [SDP-483] Api survey tag fix

- lib/tasks/admin.rake
Code can check for the role with `user.has_role? :publisher`
> [SDP-472] Rake tasks to make a user a publisher

- app/models/concerns/searchable.rb
- app/models/form.rb
- app/models/question.rb
- app/models/response_set.rb
- app/models/survey.rb
- test/models/form_test.rb
- test/models/question_test.rb
- test/models/survey_test.rb
- webpack/components/FormShow.js
- webpack/components/QuestionDetails.js
- webpack/components/surveys/Show.js
Publishing something publishes its children, also adding big "DRAFT" at top of details page for draft things.
> [SDP-488]Publishing something publishes its children and childrens children

- webpack/components/QuestionForm.js
- webpack/components/QuestionItem.js
- webpack/components/ResponseSetForm.js
> [SDP-450] Further propfixes

- config/settings.yml
- features/draft_questions.feature
- features/edit_forms.feature
- features/manage_questions.feature
- features/support/env.rb
- webpack/components/QuestionForm.js
-  tested via cucumber - Added unit tests for new functionality
> SDP-487 Response type display

- app/serializers/form_serializer.rb
- app/serializers/questions_serializer.rb
- app/serializers/survey_serializer.rb
- app/serializers/value_sets_serializer.rb
- public/api/vocab.yaml
- test/fixtures/forms.yml
- test/fixtures/questions.yml
- test/fixtures/response_sets.yml
- test/fixtures/surveys.yml
- test/support/schemas/forms/show.json
- test/support/schemas/questions/show.json
- test/support/schemas/result_sets/show.json
- test/support/schemas/surveys/show.json
Added published_by field to API serializers for:
forms
questions
response sets
surveys
Modified relevant fixtures and updated API schema
Updated API swagger doc to reflect changes
Added User definition to API swagger doc
> [SDP-508] API support for Published By

- app/serializers/form_questions_serializer.rb
- public/api/vocab.yaml
- test/fixtures/form_questions.yml
- test/support/schemas/forms/show.json
> [SDP-507] API Program Defined Variable

- app/views/forms/redcap.xml.erb
> [SDP-420] Updating redcap xm export template to use program defined variable

- webpack/components/NestedSearchBar.js
- webpack/containers/QuestionModalContainer.js
- webpack/reducers/forms_reducer.js
- na Added unit tests for new functionality
> [SDP-528, 529, 530]Form edit page bug fixes

- features/edit_forms.feature
- features/edit_questions.feature
- features/export_forms.feature
- features/manage_response_sets.feature
- features/manage_surveys.feature
- features/usage.feature
- webpack/components/DashboardSearch.js
- webpack/components/FormEdit.js
- webpack/components/NestedSearchBar.js
- webpack/components/QuestionForm.js
- webpack/components/ResponseSetForm.js
- webpack/components/SearchResult.js
- webpack/components/SurveyEdit.js
- webpack/containers/CodedSetTableEditContainer.js
- webpack/containers/Help.js
- webpack/styles/base/_colors.scss
- webpack/styles/layouts/_footer.scss
- webpack/styles/layouts/_showpageheader.scss
- webpack/styles/navigation/_nav.scss
- webpack/styles/widgets/_searchresults.scss
First set of 508 compliance issues, fixes most of the true 'Errors' seen using the WAVE tool.
Fixes:
- Contrast Errors
- Empty link errors
- Form label errors
- Table header errors
> [SDP-526,533(partly),537,558] 508 Compliance Errors

- config/initializers/session_store.rb
- n\a Added unit tests for new functionality
> [SDP-545] Secure cookie fix

- app/controllers/api/application_controller.rb
- app/models/form.rb
- app/models/survey.rb
- n\a Added unit tests for new functionality
- n\a If any changes were made to config/routes.rb run `rake jsroutes:generate`
> Brakeman fixes

- webpack/components/surveys/Show.js
> [SDP-517] Added links to form survey

- features/step_definitions/survey_steps.rb
- webpack/components/SearchResult.js
- webpack/components/SurveyFormList.js
- webpack/reducers/surveys_reducer.js
- webpack/styles/layouts/_survey_edit.scss
- webpack/styles/widgets/_searchresults.scss
Updating Survey edit page to use nice widget for forms
Also bonus fix for bug when you hit 'move up' on a survey form.
> [SDP-531]Updating Survey edit page to use nice widget for forms

- app/serializers/form_questions_serializer.rb
- app/serializers/form_serializer.rb
- app/serializers/program_serializer.rb
- app/serializers/questions_serializer.rb
- app/serializers/survey_serializer.rb
- app/serializers/system_serializer.rb
- app/serializers/value_sets_serializer.rb
- public/api/vocab.yaml
- test/support/schemas/questions/show.json
- test/support/schemas/result_sets/show.json
Added question type to question
Added source as 'publisher' to response set
Updated relevant schema
Added base path to swagger document
> [SDP-519] [SDP-521] [SDP-557] API Updates for Response Set and Question

- app/serializers/questions_serializer.rb
> Fixing API error when question has no type

- Rakefile
- package.json
> [SDP-559] Added swagger validation rake task

- app/controllers/landing_controller.rb
- app/models/concerns/searchable.rb
> [SDP-576] Fix analytics count to match what user can search

- .eslintrc
- app/models/user.rb
- config/initializers/devise.rb
- config/webpack.config.js
- webpack/containers/App.js
- webpack/containers/Header.js
- N\A Added unit tests for new functionality
- N\A Added cucumber tests for any new functionality
- N\A If any database changes were made, run `rake generate_erd` to update the README.md
- N\A If any changes were made to config/routes.rb run `rake jsroutes:generate`
> Disable login header

- webpack/components/QuestionForm.js
- webpack/components/ResponseSetDetails.js
- webpack/components/ResponseSetDragWidget.js
- webpack/containers/QuestionModalContainer.js
> [SDP-585] Fix 508 issue and make it so RS source links to vads page

- app/controllers/landing_controller.rb
- config/settings.yml
- webpack/containers/App.js
- webpack/containers/DashboardContainer.js
- webpack/containers/Header.js
- webpack/containers/Help.js
- webpack/styles/navigation/_nav.scss
Simple PR to add a version number to setting file and display in Help drop down and in Footer for reference. 0.6 version is derived from the number of pushes up to master since the development branch was created.
> [SDP-589] App version

- webpack/components/NestedSearchBar.js
- webpack/containers/CodedSetTableEditContainer.js
- webpack/styles/widgets/_search.scss
This story was for Dashboard Container, Coded Set Edit Container, and Comment List. I went through all three, Dashboard was changed in the previous PR and comment list does not need any changes as far as I could tell.
> [SDP-594] Limiting Code Search Network Request

- features/session.feature
- features/step_definitions/common_steps.rb
- features/step_definitions/session_steps.rb
- webpack/components/accounts/ProfileEditor.js
- webpack/components/accounts/SettingsModal.js
- webpack/components/accounts/SignUpModal.js
- webpack/containers/App.js
- webpack/styles/layouts/_form_edit.scss
- webpack/styles/layouts/_survey_edit.scss
Kitchen sink PR, Adding program and system filtering in User register / profile edit modals, making selected forms and questions lists bigger on survey and form edit pages, fixing profile edit bug, improving performance by removing anon functions in App.js render method
> [SDP-560, 561, 609]Adding program and system filtering, bug fixes and perf improvements

- app/serializers/questions_serializer.rb
- app/serializers/value_sets_serializer.rb
- public/api/vocab.yaml
- test/fixtures/questions.yml
- test/fixtures/response_sets.yml
- test/support/schemas/questions/show.json
- test/support/schemas/result_sets/show.json
Updated relevant serializers
Updated fixtures and schemas
Updated swagger yml
- [N/A] If any HTML was added or modified check to make sure it was still 508 compliant with WAVE tool / carried over any attributes from similar sections
> [SDP-521] Add response type and value set oid to API

- webpack/components/QuestionForm.js
- webpack/components/ResponseSetForm.js
- webpack/containers/QuestionEditContainer.js
- webpack/middleware/response_set_from_search.js
- webpack/store/configure_store.js
> [SDP 592] Question Performance Tweaks

- features/step_definitions/common_steps.rb
- features/step_definitions/form_steps.rb
- features/step_definitions/question_steps.rb
- test/frontend/components/form_question_list_test.js
- test/frontend/components/response_set_drag_widget_test.js
- webpack/components/SearchResult.js
- webpack/styles/widgets/_searchresults.scss
Thinned out the SearchResult widget as much as possible while keeping display in tact
> [SDP-595] Widget Thinning

- app/controllers/api/forms_controller.rb
- app/controllers/api/questions_controller.rb
- app/controllers/api/response_sets_controller.rb
- app/controllers/api/surveys_controller.rb
- app/controllers/forms_controller.rb
- app/controllers/questions_controller.rb
- app/controllers/response_sets_controller.rb
- app/controllers/surveys_controller.rb
- app/models/concerns/versionable.rb
- app/models/form_question.rb
- app/models/survey_form.rb
- app/serializers/es_form_serializer.rb
- app/serializers/es_survey_serializer.rb
- app/views/response_sets/index.json.jbuilder
- app/views/surveys/index.json.jbuilder
Rails DB access improvements through includes() and json template tweaks. Also small ES reindexing improvements that apply to survey edit performance.
> [SDP-631, 647] Backend Performance Improvements

- webpack/components/QuestionForm.js
- webpack/components/ResponseSetForm.js
- webpack/containers/FormsEditContainer.js
- webpack/containers/SurveyEditContainer.js
Quick fix of some header order issues I missed.
> [SDP-654] Fixing header ordering

- package.json
- test/frontend/components/form_show_test.js
- webpack/components/FormShow.js
- webpack/styles/master.scss
- webpack/styles/widgets/_pagination.scss
Implements pagination on the form show page to improve rendering speed and usability.
> [SDP-656] Form paging

- .rubocop.yml
- app/controllers/surveys_controller.rb
- app/models/question.rb
- features/draft_questions.feature
- features/step_definitions/draft_steps.rb
- features/step_definitions/question_steps.rb
- features/step_definitions/response_set_steps.rb
- lib/sdp/importers/redcap.rb
- test/elastic_helpers.rb
- test/fixtures/response_types.yml
Changes the redcap importer to allow validation of response_type
> [SDP-679] Redcap import update

- config/settings.yml
Just incrementing the version number.
> [End of Sprint] Version update

- webpack/components/SurveyEdit.js
- webpack/reducers/forms_reducer.js
- webpack/reducers/helpers.js
- webpack/reducers/questions_reducer.js
- webpack/reducers/response_sets_reducer.js
- webpack/reducers/surveys_reducer.js
Pulled out common reducer code into a helpers file. Replaced common code in the reducers where I could.
Also made a change to SurveyEdit, so it now works in the same way as FormEdit.
> [SDP-452] Refactor reducers

- webpack/components/FormEdit.js
- webpack/containers/FormsEditContainer.js
> [SDP-697] Reducing renders on form edit page

- package.json
- test/frontend/components/accounts/settings_modal_test.js
- webpack/components/accounts/ProfileEditor.js
- webpack/containers/App.js
- n/a If any HTML was added or modified check to make sure it was still 508 compliant with WAVE tool / carried over any attributes from similar sections
> SDP-711 Disable profile update

- docs/git-workflow.md
> [SDP-721] Initial draft of a git workflow

- webpack/components/DashboardSearch.js
- webpack/components/NestedSearchBar.js
- webpack/containers/response_sets/ResponseSetDragWidget.js
Quick bug fix and fixes for 508 feedback
> [SDP-744,747,748] Fixed aria labels and submit on load more bug

- app/jobs/sync_index_job.rb
- app/serializers/es_form_serializer.rb
- app/serializers/es_question_serializer.rb
- app/serializers/es_response_set_serializer.rb
- app/serializers/es_survey_serializer.rb
- lib/sdp/elastic_search.rb
- lib/tasks/elasticsearch.rake
Makes sure `rake es:sync` finishes before exiting the rake task.
> [SDP-743] Es sync

- app/controllers/api/forms_controller.rb
- app/controllers/api/programs_controller.rb
- app/controllers/api/questions_controller.rb
- app/controllers/api/response_sets_controller.rb
- app/controllers/api/surveys_controller.rb
- app/controllers/api/systems_controller.rb
- test/controllers/api/forms_controller_test.rb
- test/controllers/api/questions_controller_test.rb
- test/controllers/api/response_sets_controller_test.rb
- test/controllers/api/surveys_controller_test.rb
> Setting api limits and limiting to published and owned content only

- webpack/actions/questions_actions.js
- webpack/components/questions/QuestionEdit.js
- webpack/containers/questions/QuestionEditContainer.js
- webpack/containers/questions/QuestionModalContainer.js
- webpack/containers/response_sets/ResponseSetDragWidget.js
Question form now working with full objects instead of ids
> [SDP-739] Question form normalizr

- features/manage_response_sets.feature
- features/step_definitions/response_set_steps.rb
- webpack/components/questions/QuestionEdit.js
- webpack/containers/CodedSetTableEditContainer.js
- webpack/styles/elements/_table.scss
Following  https://www.section508.va.gov/support/html/7_0.asp Documentation I revisited our tables to make sure they abide by the 508 rules for a "simple data table"
> [SDPV-14] 508 tables

- lib/sdp/importers/spreadsheet.rb
- lib/tasks/spreadsheet.rake
Added dateTime to the data types for importing so the Generic MMG can be properly imported
Created rake task to append an MMG import to an existing survey
> [SDPV-19,21] MMG Import Improvements

- lib/sdp/importers/spreadsheet.rb
- test/unit/lib/mmg_test.rb
> [SDPV-22] Tag forms on import from MMG files

- lib/tasks/cleanup.rake
Small rake task that will hopefully only be needed once.
> [SDPV-46] Rake task to clean up orphaned relationships

- webpack/components/response_sets/ResponseSetShow.js
- webpack/containers/questions/QuestionItem.js
> [SDPV-48,54] Fixing formquestion not being denormalized

- webpack/containers/DashboardContainer.js
- webpack/containers/forms/FormSearchContainer.js
- webpack/containers/questions/QuestionItem.js
- webpack/containers/questions/QuestionSearchContainer.js
- webpack/containers/response_sets/ResponseSetDragWidget.js
on on SurveyEdit (not working at all) and one on all where changing search term doesn't reset page count. See story for more info.
> [SDPV-63] Two bug fixes for load more buttons, 

- docs/js-dev-guide.md
- npm-shrinkwrap.json
- package.json
- test/frontend/components/modal_dialog_test.js
- test/frontend/components/questions/question_edit_test.js
- test/frontend/test_helper.js
Fixed the deprecation warning resulting from the React upgrade: https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html
> [SDPV-1] Update testutils location

- features/edit_questions.feature
- webpack/actions/search_results_actions.js
- webpack/components/SearchResultList.js
- webpack/components/questions/QuestionEdit.js
- webpack/containers/questions/QuestionEditContainer.js
- webpack/containers/questions/QuestionModalContainer.js
Once a user types in 10 or more characters in the content or description
fields for a question, the application will attempt to find duplicate
questions and display them in the footer of the form.
> [SDPV-59] Implemented duplicate question suggestions

- .rubocop.yml
- app/serializers/value_sets_serializer.rb
- config/environments/test.rb
- test/fixtures/response_sets.yml
- test/models/response_set_test.rb
- test/unit/serializer/value_sets_serializer_test.rb
- n\a If any changes were made to config/routes.rb run `rake jsroutes:generate`
- n\a If any HTML was added or modified check to make sure it was still 508 compliant with WAVE tool / carried over any attributes from similar sections
> Valueset url update

- app/controllers/registrations_controller.rb
- app/models/user.rb
- test/unit/serializer/value_sets_serializer_test.rb
- webpack/containers/App.js
> [SDPV-113] Allow user to update profile when registration disabled

- app/controllers/admin_controller.rb
- app/controllers/administrators_controller.rb
- app/controllers/concepts_controller.rb
- app/controllers/forms_controller.rb
- app/controllers/publishers_controller.rb
- app/controllers/question_types_controller.rb
- app/controllers/questions_controller.rb
- app/controllers/response_sets_controller.rb
- app/controllers/surveys_controller.rb
- app/models/ability.rb
- test/controllers/api/forms_controller_test.rb
- test/controllers/api/programs_controller_test.rb
- test/controllers/api/questions_controller_test.rb
- test/controllers/api/response_sets_controller_test.rb
- test/controllers/api/surveys_controller_test.rb
- test/controllers/api/systems_controller_test.rb
- test/controllers/survey_controller_test.rb
- test/fixtures/surveys.yml
- test/support/schemas/surveys/show.json
> [SDPV-120] Ability cleanup

- app/models/ability.rb
- webpack/components/sections/SectionShow.js
- webpack/components/surveys/SurveyShow.js
> [SDPV-98] Redcap surveys

- config/settings.yml
- n\a Added unit tests for new functionality
- n\a  Added cucumber tests for any new functionality
- n\a Passed all cucumber tests using `bundle exec cucumber`  -- cucumber is broken on my machine but I'm pretty sure that a one line config change will not effect anything
- n\a Passed overcommit hooks, including running all code through Rubocop
- n\a If any changes were made to config/routes.rb run `rake jsroutes:generate`
- n\a If any HTML was added or modified check to make sure it was still 508 compliant with WAVE tool / carried …
> Updating the version number

- webpack/containers/questions/QuestionItem.js
- webpack/containers/questions/QuestionSearchContainer.js
- webpack/containers/sections/SectionSearchContainer.js
Fixing suggestions not showing up for DashboardSearchbars not on the dashboard
> Fixes suggestions not showing up on nested search bars (not on the dash)

- db/migrate/20171026122938_change_question_categories.rb
> Attempting to fix the migration issue on demo

- db/migrate/20171103123808_rename_question_type_to_category.rb
*note: once this is merged the db will have to be rolledback and then re-migrated in development
> [SDPV-195] Migration fix for subcategories

- db/migrate/20171103123808_rename_question_type_to_category.rb
*note: when this is merged any environment where this is running needs to be rolledback and then re-migrated.
> [SDPV-195] Fixing issue with subcategories not saving

- lib/sdp/elastic_search.rb
> Uncommenting sorting code

- features/advance_search.feature
- lib/sdp/elastic_search.rb
- webpack/components/DashboardSearch.js
- webpack/components/sections/SectionEdit.js
- webpack/containers/CodedSetTableEditContainer.js
- Sort by program use
- Rename tags column headers
- add info pop-up describing how to use tags (users said they needed something more explicit for this than the step by step walkthrough / help docs
> [SDPV-192,193,183] Program use

- app/views/questions/_question.json.jbuilder
- app/views/sections/_section.json.jbuilder
- db/schema.rb
- features/edit_questions.feature
- features/edit_sections.feature
- features/manage_surveys.feature
- features/step_definitions/section_steps.rb
- test/frontend/components/survey/survey_show_test.js
- webpack/components/SearchResult.js
- webpack/components/questions/QuestionShow.js
- webpack/components/sections/SectionList.js
- webpack/components/sections/SectionShow.js
- webpack/components/shared_show/GroupLookUp.js
- webpack/components/surveys/SurveyList.js
- webpack/components/surveys/SurveyShow.js
- webpack/schema.js
- webpack/styles/layouts/_panels.scss
> [SDPV-122,209] Expand display of relationships

- lib/sdp/importers/checklist.rb
- lib/tasks/checklist.rake
- test/fixtures/files/checklist/datatype_sub_question.xml
- test/fixtures/files/checklist/header.xml
- test/fixtures/files/checklist/sections.xml
- test/fixtures/files/checklist/simple_question.xml
- test/fixtures/files/checklist/sub_question.xml
- test/unit/lib/checklist_test.rb
College of American Pathologists (CAP) provide checklists in an XML
format.
> [SDPV-208] Implemented importer for CAP Checklists

- app/controllers/elasticsearch_controller.rb
- features/advance_search.feature
- lib/sdp/elastic_search.rb
- webpack/actions/search_results_actions.js
- webpack/components/DashboardSearch.js
- webpack/containers/DashboardContainer.js
- webpack/styles/elements/_input.scss
- webpack/styles/widgets/_recentitems.scss
> [SDPV-199] Group dash

- webpack/components/CodedSetTable.js
- webpack/containers/CodedSetTableEditContainer.js
- webpack/containers/DashboardContainer.js
- webpack/containers/Help.js
- webpack/containers/questions/QuestionEditContainer.js
- webpack/containers/response_sets/ResponseSetEditContainer.js
> [SDPV] Fixing character droping issue in i.e.

- lib/tasks/usage.rake
Only adding a rake task to generate reuse metrics
> [SDPV-210] Rake task to compute reuse metrics

- app/controllers/questions_controller.rb
- app/controllers/response_sets_controller.rb
- app/controllers/sections_controller.rb
- app/controllers/surveys_controller.rb
- app/models/concerns/groupable.rb
- app/models/concerns/versionable.rb
- app/models/question.rb
- app/models/response_set.rb
- app/models/section.rb
- app/models/survey.rb
- test/controllers/questions_controller_test.rb
- test/controllers/response_sets_controller_test.rb
- test/controllers/sections_controller_test.rb
- test/controllers/survey_controller_test.rb
- test/models/survey_test.rb
> [SDPV-220] Cascade groups

- webpack/containers/AdminPanel.js
- webpack/containers/DashboardContainer.js
- webpack/containers/Help.js
- webpack/containers/questions/QuestionEditContainer.js
- webpack/containers/questions/QuestionShowContainer.js
- webpack/containers/response_sets/ResponseSetEditContainer.js
- webpack/containers/response_sets/ResponseSetShowContainer.js
- webpack/containers/sections/SectionEditContainer.js
- webpack/containers/sections/SectionShowContainer.js
- webpack/containers/surveys/SurveyEditContainer.js
- webpack/containers/surveys/SurveyShowContainer.js
- webpack/schema.js
Fixing the section bug and updating step-by-step help and help documentation
> [SDPV-223,254] Help documentation & section overwriting bug

- Jenkinsfile
Test reports are archived to the jenkins master
- [ NA ] Added unit tests for new functionality
- [ NA ] Passed all unit tests using `rails test` with 90%+ coverage
- [ NA ] Added cucumber tests for any new functionality
- [ NA ] Passed all cucumber tests using `bundle exec cucumber`
- [ x ] Passed overcommit hooks, including running all code through Rubocop
- [ NA ] If any database changes were made, run `rake generate_erd` to update the README.md
- [ NA ] If any changes were made to config/routes.rb run `rake jsroutes:generate`
- [ NA ] If any HTML was added or modified check to make sure it was still 508 compliant with WAVE tool / carried over any attributes from similar sections
> Archive reports [SDPV-4]

- webpack/containers/sections/SectionEditContainer.js
- webpack/containers/surveys/SurveyEditContainer.js
Fixed some errors that were being reported by eslint
- [ NA ] Added unit tests for new functionality
- [ x ] Passed all unit tests using `rails test` with 90%+ coverage
- [ NA ] Added cucumber tests for any new functionality
- [ NA ] Passed all cucumber tests using `bundle exec cucumber`
- [ x ] Passed overcommit hooks, including running all code through Rubocop
- [ NA ] If any database changes were made, run `rake generate_erd` to update the README.md
- [ NA ] If any changes were made to config/routes.rb run `rake jsroutes:generate`
- [ NA ] If any HTML was added or modified check to make sure it was still 508 compliant with WAVE tool / carried over any attributes from similar sections
> Addressed some eslint errors

- features/session.feature
- webpack/containers/DashboardContainer.js
- webpack/containers/Help.js
> [SDPV-255] First time login modal

- app/views/api/fhir/questionaires/_show.json.jbuilder
- test/controllers/api/fhir/questionaires_controller_test.rb
> [SDPV-273] Adding program variables to the FHIR API

- config/settings.yml
> Updating release number 1.6

- features/admin_panel.feature
- webpack/components/questions/QuestionEdit.js
- webpack/components/response_sets/ResponseSetEdit.js
- webpack/containers/AdminPanel.js
- webpack/containers/CodedSetTableEditContainer.js
- webpack/containers/sections/SectionEditSearchContainer.js
> [SDPV-281,284,285] Admin panel updates

- Gemfile
- Gemfile.lock
- Jenkinsfile
- Rakefile
- features/admin_panel.feature
- features/draft_questions.feature
- features/edit_questions.feature
- features/manage_forms.feature
- features/manage_questions.feature
- features/manage_response_sets.feature
- features/manage_surveys.feature
- features/session.feature
- features/step_definitions/common_steps.rb
- features/support/env.rb
- features/support/test_helper.rb
- lib/tasks/cucumber.rake
Updates to allow headless cucumber testing (and fix to rebase error).
>  [ECPAAS-152] Headless Testing Fix

- app/controllers/questions_controller.rb
- app/controllers/response_sets_controller.rb
- app/controllers/sections_controller.rb
- app/controllers/surveys_controller.rb
- app/models/concerns/groupable.rb
- app/models/concerns/versionable.rb
- app/models/question.rb
- app/models/response_set.rb
- app/models/section.rb
- features/manage_surveys.feature
- lib/sdp/comments_notifier.rb
- test/controllers/questions_controller_test.rb
- test/controllers/response_sets_controller_test.rb
- test/controllers/survey_controller_test.rb
- test/frontend/components/survey/survey_edit_test.js
- webpack/actions/survey_actions.js
- webpack/components/accounts/ProfileEditor.js
- webpack/components/surveys/ProgSysEditModal.js
- webpack/components/surveys/SurveyEdit.js
- webpack/containers/surveys/SurveyEditContainer.js
- webpack/styles/layouts/_survey_edit.scss
Program and system user assigned & validations to prevent issues with appscan
> [SDPV-327,328,329] Prog sys edit

- app/serializers/section_nested_items_serializer.rb
- app/views/api/fhir/questionaires/_nested_section.json.jbuilder
- app/views/api/fhir/questionaires/_question.json.jbuilder
- app/views/api/fhir/questionaires/_show.json.jbuilder
- public/api/vocab.yaml
Updating API to account for nested sections and adding fhir endpoints to swagger docs.
> [SDPV-237,248,249] Nested API

- config/settings.yml
- public/api/vocab.yaml
- webpack/components/SearchResult.js
> Fixing display bug and changing tag to 1.6

- webpack/components/questions/QuestionShow.js
- webpack/components/response_sets/ResponseSetShow.js
- webpack/components/sections/SectionShow.js
- webpack/components/surveys/SurveyShow.js
> [SDPV-180] UI: Add workflow status to object details headers

- config/settings.yml
> Taggin 1.7 alpha

- Rakefile
- lib/tasks/cucumber.rake
> Only run cucumber once in bin/rake

- Jenkinsfile
Minor change to message wording (using the same branch that was just merged, since it was not deleted post-request)
> Slack integration

- app/models/concerns/groupable.rb
- app/models/question.rb
- app/models/response_set.rb
- app/models/section.rb
- app/models/survey.rb
- app/views/questions/_question.json.jbuilder
- app/views/response_sets/_response_set.json.jbuilder
- app/views/sections/_section.json.jbuilder
- app/views/surveys/show.json.jbuilder
- features/group_info.feature
- features/step_definitions/common_steps.rb
- test/frontend/containers/response_sets/response_set_drag_widget_test.js
- webpack/components/SearchResult.js
- webpack/containers/DashboardContainer.js
- webpack/containers/response_sets/ResponseSetDragWidget.js
- webpack/styles/iconMap.js
- webpack/styles/master.scss
- webpack/styles/widgets/_groups.scss
- webpack/styles/widgets/_searchresults.scss
396- Collapsable elements on question edit page are now distinct ids on left and right side of screen
399- Group permissions update elasticsearch properly on cascade [bug fix]
404- Integration / testing of group home page UI work (Mike may add more Cucumber tests)
405- Revision history maps _id fields to human readable names
> [SDPV-396,399,404,405] Smaller sprint stories

- Jenkinsfile
- config/settings/test.yml
- docs/elastic_search_schema.json
- lib/tasks/admin.rake
- lib/tasks/data.rake
- lib/tasks/elasticsearch.rake
This is a bit of an odd pull request. It updates our Jenkinsfile so that we can fully test elasticsearch in CI. It does all of the OpenShift stuff to spin up and shut down an ephemeral elasticsearch instance.
There is a new rake task to perform the integration test. There are also bug fixes for some of our user related admin tasks.
This PR can be squashed into a single commit. I am including the commit that breaks the build as proof that the test does actually detect when things go south with elasticsearch.
> [SDPV-374] Elasticsearch integration testing

- config/settings.yml
> Just the 1.9 tag

- .gitignore
- app/controllers/questions_controller.rb
- app/controllers/sections_controller.rb
- app/controllers/surveys_controller.rb
- features/manage_surveys.feature
- test/models/survey_test.rb
- [ x] Added unit tests for new functionality
- [ x] Passed all unit tests using `rails test` with 90%+ coverage
- [ x] Added cucumber tests for any new functionality
- [ x] Passed all cucumber tests using `bundle exec cucumber`
- [ x] Passed overcommit hooks, including running all code through Rubocop
- [ x] If any database changes were made, run `rake generate_erd` to update the README.md
- [ x] If any changes were made to config/routes.rb run `rake jsroutes:generate`
- [ x] If any HTML was added or modified check to make sure it was still 508 compliant with WAVE tool / carried over any attributes from similar …
> Feature cascade groups

- app/controllers/admin/preferred_content_controller.rb
- config/settings.yml
- webpack/components/surveys/SurveyDedupe.js
- webpack/styles/layouts/_section_edit.scss
> [SDPV-493] Tagging 1.9, Curation wizard UI improvements

- app/controllers/elasticsearch_controller.rb
- app/serializers/es_response_set_serializer.rb
- features/advance_search.feature
- lib/sdp/elastic_search.rb
- test/unit/lib/elastic_search_test.rb
- webpack/actions/search_results_actions.js
- webpack/components/DashboardSearch.js
- webpack/containers/DashboardContainer.js
- webpack/styles/widgets/_search.scss
Note to reviewer: This puts everything in the advanced filter modal, it was discussed that this would be the initial implementation and based on user feedback there might be some filters moved to the Dashboard or other redesigns
> [SDPV-186] Working new advanced filters with initial UI

- docs/elastic_search_schema.json
- features/import_survey.feature
- features/manage_response_sets.feature
- features/manage_surveys.feature
Simple cucumber fix - making a PR to test the build in the dev cluster.
> Fixing cucumber test for build pipeline

- Jenkinsfile
Just changing jenkins timeout to hopefully pass builds in demo
> Extended timeout time

- Gemfile.lock
- app/controllers/elasticsearch_controller.rb
- app/serializers/es_survey_serializer.rb
- config/settings.yml
- docs/elastic_search_schema.json
- features/advance_search.feature
- lib/sdp/elastic_search.rb
- webpack/actions/search_results_actions.js
- webpack/components/DashboardSearch.js
- webpack/components/SearchResult.js
- webpack/containers/DashboardContainer.js
Adding filter for OMB approval date and bumping the version to 1.10
> [SDPV-553] Omb date filter & 1.10 tag

- features/manage_surveys.feature
- webpack/components/surveys/SurveyDedupe.js
- [ x] Added unit tests for new functionality
- [ x] Passed all unit tests using `rails test` with 90%+ coverage
- [ x] Added cucumber tests for any new functionality
- [ x] Passed all cucumber tests using `bundle exec cucumber`
- [ x] Passed overcommit hooks, including running all code through Rubocop
- [ x] If any database changes were made, run `rake generate_erd` to update the README.md
- [ x] If any changes were made to config/routes.rb run `rake jsroutes:generate`
- [ x] If any HTML was added or modified check to make sure it was still 508 compliant with WAVE tool / carried over any attributes from similar …
> [SDPV-492] Feature confirm replace

- db/schema.rb
- features/advance_search.feature
- features/step_definitions/common_steps.rb
- webpack/components/DashboardSearch.js
- webpack/components/NestedSearchBar.js
- webpack/components/SearchResultList.js
- webpack/styles/elements/_buttons.scss
- webpack/styles/layouts/_response_set.scss
- webpack/styles/widgets/_search.scss
> Adv filter

- config/settings.yml
> 1.11 Tag update

- .gitignore
- app/models/section.rb
- features/edit_sections.feature
- lib/tasks/cucumber.rake
- webpack/components/surveys/SurveyShow.js
This is just a quick bugfix for a small button rendering bug I noticed when setting up the demo, and a more critical bug with deleting nested sections which causes UI rendering issues because of a broken nil pointer.
> [SDPV-623] Delete sect bugfix

- Rakefile
- app/models/concerns/versionable.rb
- app/models/section.rb
- lib/sdp/importers/phin_vads_importer.rb
- lib/tasks/admin.rake
- lib/tasks/cucumber.rake
- package-lock.json
- package.json
- test/frontend/test_helper.js
- yarn.lock
Administrative updates - updated node packages so there aren't vulnerabilities and resolved issues with the update. Fixed a couple minor bugs with the value set sync not properly configuring the proxy.
> [SDPV-582,626,627] Node and proxy updates

- public/api/index.html
Fixed two issues:
1. [SDPV-580] API endpoint works only when the endpoint is followed by a / ("slash")
2. [SDPV-616] Swagger UI not rendering in CDC environment
> Fixed [SDPV-580] and [SDPF-616]

- app/models/ability.rb
- features/manage_surveys.feature
Patch test to fix issue with 1.12 before putting in CR - will be verified by Kelly in Demo then put in separately with the 1.12 changes.
> Adding test to verify fix for request

- app/models/ability.rb
- features/manage_surveys.feature
> [SDPV-654] Applying patch to master

- Jenkinsfile
- app/controllers/surveys_controller.rb
- webpack/components/questions/QuestionShow.js
- webpack/components/response_sets/ResponseSetShow.js
- webpack/components/sections/SectionShow.js
- webpack/components/surveys/SurveyShow.js
- webpack/containers/Header.js
- webpack/containers/Help.js
> [SDPV-688,682,683,693] Tab Visibility, Help Link, Timeout increase

- .gitignore
- Gemfile
- Gemfile.lock
- README.md
- features/help.feature
- package.json
- webpack/containers/Header.js
- webpack/containers/Help.js
- windows/README.md
- yarn.lock
> [SDPV-463] What's New Tab Addition

- features/draft_questions.feature
- features/edit_questions.feature
- features/manage_response_sets.feature
- features/manage_sections.feature
- features/manage_surveys.feature
- features/usage.feature
- webpack/components/questions/QuestionShow.js
- webpack/components/response_sets/ResponseSetShow.js
- webpack/components/sections/SectionShow.js
- webpack/components/surveys/SurveyShow.js
> [SDPV-698] Publish confirm

- app/controllers/api/response_sets_controller.rb
> oid parameter [SDPV-712]

- config/settings.yml
- public/api/vocab.yaml
- webpack/containers/CodedSetTableEditContainer.js
- webpack/containers/Help.js
- webpack/containers/questions/QuestionEditContainer.js
- webpack/containers/sections/SectionEditContainer.js
- webpack/containers/surveys/SurveyEditContainer.js
> [SDPV-730] Update In-app docs

- Jenkinsfile
- app/controllers/concept_service_controller.rb
- features/support/env.rb
Debugging and issue in cdc Dev/Test
> Debugging net:opentimeout

- Jenkinsfile
Each container image built for deployment to dev/test or demo environments will be scanned with twistlock.
> [SDPV-771] Added Twistlock scanning to pipeline

- app/serializers/es_response_set_serializer.rb
- docs/elastic_search_schema.json
- lib/sdp/elastic_search.rb
> [SDPV-768] Exact match

- app/views/questions/_epi_info_question_field.xml.erb
- app/views/sections/_epi_info_section_field.xml.erb
- app/views/sections/_epi_info_section_page.xml.erb
- app/views/surveys/epi_info.xml.erb
> [SDPV-697] Epi info pages

- webpack/actions/survey_actions.js
- webpack/containers/surveys/SurveyDedupeContainer.js
> [SDPV-680] Loading spinner from knowledge transfer

- docs/elastic_search_schema.json
- lib/sdp/elastic_search.rb
> [SDPV-636] Token fix

- app/jobs/update_index_job.rb
- app/models/survey.rb
- app/serializers/es_survey_serializer.rb
- docs/elastic_search_schema.json
- features/advance_search.feature
- features/edit_questions.feature
- lib/sdp/elastic_search.rb
- lib/sdp/importers/spreadsheet.rb
- test/jobs/update_index_job_test.rb
- webpack/components/DashboardSearch.js
- webpack/components/questions/QuestionShow.js
- webpack/components/response_sets/ResponseSetShow.js
- webpack/components/sections/SectionShow.js
- webpack/components/surveys/SurveyShow.js
- webpack/containers/Help.js
- webpack/containers/surveys/SurveyDedupeContainer.js
- webpack/containers/surveys/SurveyImportContainer.js
> [SDPV-777,802,804,805,817,824] Search changes and misc sprint work

- docs/elastic_search_schema.json
Updated elastic search filter to include google suggested stopwords.  In addition, included three additional words identified by the user work group.
> SDPV-808 - added Stopwords

- lib/sdp/elastic_search.rb
- [X ] Passed all unit tests using `rails test` with 90%+ coverage
- [X ] Passed overcommit hooks, including running all code through Rubocop`
- [X ] Ensure all code has been appropriately commented inline per standard convention
> [SDPV-662] - remove retired content from curation wiz search

- webpack/components/surveys/SurveyDedupe.js
- [c] Passed overcommit hooks, including running all code through Rubocop
> [SDPV-663,852] Adding link for questions and rs, making matches human readable

- Jenkinsfile
- config/settings.yml
This change adds an additional stage to the Jenkins pipeline that scans the SDP-V codebase using the SonarQube tool.  It also updates the Jenkins build page with the results of the scan.
> [SDPV-848] Added SonarQube scan stage

- Jenkinsfile
> Launch elasticsearch 6 image for tests

- .rubocop.yml
- config/environments/production.rb
> Only log WARN and higher messages in production

- app/controllers/concept_service_controller.rb
- config/settings.yml
- features/manage_notifications.feature
- features/step_definitions/notification_steps.rb
> Fixing concept controller typo and bumping version

- app/views/layouts/landing.html.erb
- features/manage_surveys.feature
- lib/tasks/usage.rake
- webpack/components/surveys/SurveyDedupe.js
- webpack/containers/surveys/SurveyDedupeContainer.js
> [SDPV-853, 855] - Curation wizard and rake task query addons

- webpack/containers/Help.js
Per Product Owner request, updated release notes for Release 1.15, 1.16, and 1.17.
> [SDPV-Product Owner] - Updated release notes

- config/settings.yml
- webpack/containers/Help.js
> SDPV - Whats new 1.18

- webpack/containers/Help.js
Updated what's new content for 1.18.
> SDPV - What's New 1.18 content update

- app/controllers/elasticsearch_controller.rb
- config/settings.yml
- features/session.feature
- lib/sdp/elastic_search.rb
- lib/tasks/usage.rake
- webpack/components/DashboardSearch.js
- webpack/components/accounts/ProfileEditor.js
- webpack/components/surveys/ProgSysEditModal.js
- webpack/containers/Help.js
> [SDPV-584] Advanced Dupe Questions

- features/edit_questions.feature
- features/manage_response_sets.feature
- features/step_definitions/response_set_steps.rb
- webpack/components/questions/QuestionShow.js
- webpack/components/response_sets/ResponseSetShow.js
- webpack/components/sections/SectionShow.js
- webpack/components/surveys/SurveyShow.js
> [SDPV-742] Pagination

- config/settings.yml
- webpack/containers/Help.js
> SDPV - What's new 1.19

- webpack/components/questions/QuestionShow.js
- webpack/components/response_sets/ResponseSetShow.js
- webpack/components/sections/SectionShow.js
- webpack/components/surveys/SurveyShow.js
- webpack/containers/Header.js
- webpack/containers/Help.js
- 1 failure with suggested edit (needs review)
> [SDPV-469, 920, 924] - Added tags and PHIN VADS linkage

- lib/sdp/importers/spreadsheet.rb
> [SDPV-469] - OID import file

- app/serializers/es_question_serializer.rb
- app/serializers/es_response_set_serializer.rb
- app/serializers/es_section_serializer.rb
- app/serializers/es_survey_serializer.rb
- docs/elastic_search_question_schema.json
- docs/elastic_search_response_set_schema.json
- docs/elastic_search_section_schema.json
- docs/elastic_search_survey_schema.json
- features/edit_sections.feature
- lib/sdp/elastic_search.rb
- test/frontend/components/search_result_test.js
- webpack/components/SearchResult.js
- webpack/components/questions/QuestionShow.js
- webpack/components/sections/SectionEdit.js
- webpack/components/sections/SectionShow.js
- webpack/utilities/componentHelpers.js
- yarn.lock
Note: I was updating eslint and installation issues occurred.  Had to run a yarn install.  Check yarn.lock in this pull.  May need to be ignored.
> [SDPV - 69, 942] - Linked content and sorting for versions

- webpack/containers/Help.js
> [SDPV-970] Whats New User Document Update

- test/frontend/components/response_sets/response_set_list_test.js
- webpack/components/SearchResult.js
- webpack/components/SearchResultList.js
- webpack/containers/DashboardContainer.js
- webpack/styles/base/_colors.scss
- webpack/styles/widgets/_analytics.scss
- webpack/styles/widgets/_recentitems.scss
- x ] Ensure all code has been appropriately commented inline per standard convention
> [SDPV-1019] Preview improve

- features/cancel_buttons.feature
- features/draft_questions.feature
- features/edit_questions.feature
- features/edit_sections.feature
- features/manage_questions.feature
- features/manage_response_sets.feature
- features/manage_sections.feature
- features/manage_surveys.feature
- webpack/components/InfoModalBodyContent.js
- webpack/components/questions/QuestionEdit.js
- webpack/components/questions/QuestionShow.js
- webpack/components/response_sets/ResponseSetEdit.js
- webpack/components/response_sets/ResponseSetShow.js
- webpack/components/sections/SectionEdit.js
- webpack/components/sections/SectionShow.js
- webpack/components/shared_show/ProgramsAndSystems.js
- webpack/components/surveys/SurveyEdit.js
- webpack/components/surveys/SurveyShow.js
> [SDPV - 1014, 1015, 1016, 1017, 1018] - info buttons v2

- features/advance_search.feature
- features/cancel_buttons.feature
- features/edit_questions.feature
- features/group_info.feature
- features/session.feature
- webpack/components/DashboardSearch.js
- webpack/components/SearchResult.js
- webpack/components/SearchResultList.js
- webpack/components/questions/QuestionShow.js
- webpack/components/sections/SectionShow.js
- webpack/containers/DashboardContainer.js
- webpack/containers/Header.js
- webpack/containers/sections/SectionEditSearchContainer.js
- webpack/styles/base/_colors.scss
- webpack/styles/iconMap.js
- webpack/styles/layouts/_body.scss
- webpack/styles/navigation/_nav.scss
- webpack/styles/widgets/_analytics.scss
- webpack/styles/widgets/_search.scss
- webpack/styles/widgets/_searchresults.scss
> [SDPV-990] Dash improvements

- .rubocop.yml
- Gemfile
- Gemfile.lock
- app/controllers/api/application_controller.rb
- app/controllers/api/fhir/questionaires_controller.rb
- app/controllers/api/fhir/valuesets_controller.rb
- app/controllers/api/metrics_controller.rb
- app/controllers/api/programs_controller.rb
- app/controllers/api/questions_controller.rb
- app/controllers/api/response_sets_controller.rb
- app/controllers/api/sections_controller.rb
- app/controllers/api/surveys_controller.rb
- app/controllers/api/systems_controller.rb
- config/initializers/staccato.rb
- test/support/fakeweb.rb
Testing locally, several failures.  Pushing to check initial pass in cdc jenkins environment.  
- Rubocop (1 failure) and rails test (several failures).
> [SDPV-1021] - staccato for api metrics

- Gemfile
- Gemfile.lock
- Jenkinsfile
- lib/tasks/audit.rake
- webpack/components/DashboardSearch.js
- webpack/containers/DashboardContainer.js
- webpack/containers/Help.js
Patch of link bug and mitigate outstanding CVE
https://github.com/omniauth/omniauth/pull/809
> Link patch with omniauth protection

- features/step_definitions/question_steps.rb
- features/step_definitions/response_set_steps.rb
- features/step_definitions/section_steps.rb
- features/step_definitions/survey_steps.rb
- webpack/components/DashboardSearch.js
- webpack/containers/DashboardContainer.js
- webpack/styles/layouts/_body.scss
- webpack/styles/widgets/_analytics.scss
- webpack/styles/widgets/_search.scss
> [SDPV-1022] Multiselect filters and badges

- app/controllers/elasticsearch_controller.rb
- features/advance_search.feature
- lib/sdp/elastic_search.rb
- webpack/components/DashboardSearch.js
- webpack/containers/DashboardContainer.js
- webpack/styles/layouts/_body.scss
> [SDPV-1022] Multi select fixed

- features/edit_sections.feature
- features/import_survey.feature
- features/manage_response_sets.feature
- features/manage_sections.feature
- features/manage_surveys.feature
- features/widget.feature
- webpack/components/questions/QuestionShow.js
- webpack/components/response_sets/ResponseSetShow.js
- webpack/components/sections/SectionShow.js
- webpack/components/surveys/SurveyShow.js
- webpack/styles/layouts/_contentbox.scss
> [SDPV-1051, 1052, 1053, 1054] - Reorder components

- webpack/containers/surveys/SurveyImportContainer.js
- webpack/styles/layouts/_contentbox.scss
> [SDPV - 968, 1056] - Reorder components v2

- webpack/components/questions/QuestionShow.js
- webpack/components/response_sets/ResponseSetShow.js
- webpack/components/sections/SectionShow.js
- webpack/components/surveys/SurveyShow.js
> [SDPV-416, 969, 865, 968] - Reorder components v3

- app/controllers/elasticsearch_controller.rb
- config/settings.yml
- features/advance_search.feature
- lib/sdp/elastic_search.rb
- webpack/components/DashboardSearch.js
- webpack/containers/Help.js
- webpack/styles/navigation/_nav.scss
> What's New 1.22 content

- webpack/components/response_sets/ResponseSetShow.js
- webpack/components/surveys/SurveyShow.js
> updated order and programs and systems - bug fix

- app/helpers/epi_info_helper.rb
- features/edit_sections.feature
- webpack/components/DashboardSearch.js
- webpack/components/SearchResult.js
- webpack/components/questions/QuestionEdit.js
- webpack/containers/sections/SectionEditSearchContainer.js
> [SDPV-973] Pushing changes from last week

- Gemfile
- Gemfile.lock
- package-lock.json
- webpack/components/sections/SectionEdit.js
- webpack/components/surveys/SurveyEdit.js
> Adding position

- Gemfile
- Gemfile.lock
> updated gem wdm to 0.1.1

- webpack/containers/Help.js
> chris merge test

- webpack/containers/Help.js
Build should not pass due to fresh dev pull and previous passed PRs not merged.
Will merge this commit to test pipeline after build completes.
> [SDPV-1175] Demo decommission merge test

- webpack/containers/Help.js
> [SDPV-1181] update link

- webpack/containers/Help.js
Initial commit to add 1.23 content to the What's New page.
> [SDPV-1141] - added initial 1-23 release notes

- app/views/questions/_epi_info_question_field.xml.erb
> [SDPV-1170] - added missing field to xml template

- Gemfile
- Gemfile.lock
- app/views/questions/_epi_info_question_field.xml.erb
> Epi info export

- app/controllers/api/response_sets_controller.rb
> [SDPV-1167] - api update

- Gemfile.lock
> updated found vulnerability

- config/settings.yml
- webpack/containers/Help.js
> Updated release notes and version number
